package net.matty.bmbc.item;

import net.matty.bmbc.BetterMineBetterCraft;
import net.minecraft.world.item.Item;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class FluidStorageItems {
    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, BetterMineBetterCraft.MOD_ID);

    public static final RegistryObject<Item> HYDROGEN_CANISTER = ITEMS.register("hydrogen_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.HYDROGEN_COMPOUND));
    public static final RegistryObject<Item> HELIUM_CANISTER = ITEMS.register("helium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.HELIUM_COMPOUND));
    public static final RegistryObject<Item> LITHIUM_CANISTER = ITEMS.register("lithium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.LITHIUM_COMPOUND));
    public static final RegistryObject<Item> BERYLLIUM_CANISTER = ITEMS.register("beryllium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.BERYLLIUM_COMPOUND));
    public static final RegistryObject<Item> BORON_CANISTER = ITEMS.register("boron_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.BORON_COMPOUND));
    public static final RegistryObject<Item> CARBON_CANISTER = ITEMS.register("carbon_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.CARBON_COMPOUND));
    public static final RegistryObject<Item> NITROGEN_CANISTER = ITEMS.register("nitrogen_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.NITROGEN_COMPOUND));
    public static final RegistryObject<Item> OXYGEN_CANISTER = ITEMS.register("oxygen_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.OXYGEN_COMPOUND));
    public static final RegistryObject<Item> FLUORINE_CANISTER = ITEMS.register("fluorine_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.FLUORINE_COMPOUND));
    public static final RegistryObject<Item> NEON_CANISTER = ITEMS.register("neon_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.NEON_COMPOUND));
    public static final RegistryObject<Item> SODIUM_CANISTER = ITEMS.register("sodium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.SODIUM_COMPOUND));
    public static final RegistryObject<Item> MAGNESIUM_CANISTER = ITEMS.register("magnesium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.MAGNESIUM_COMPOUND));
    public static final RegistryObject<Item> ALUMINIUM_CANISTER = ITEMS.register("aluminium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.ALUMINIUM_COMPOUND));
    public static final RegistryObject<Item> SILICON_CANISTER = ITEMS.register("silicon_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.SILICON_COMPOUND));
    public static final RegistryObject<Item> PHOSPHORUS_CANISTER = ITEMS.register("phosphorus_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.PHOSPHORUS_COMPOUND));
    public static final RegistryObject<Item> SULFUR_CANISTER = ITEMS.register("sulfur_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.SULFUR_COMPOUND));
    public static final RegistryObject<Item> CHLORINE_CANISTER = ITEMS.register("chlorine_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.CHLORINE_COMPOUND));
    public static final RegistryObject<Item> ARGON_CANISTER = ITEMS.register("argon_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.ARGON_COMPOUND));
    public static final RegistryObject<Item> POTASSIUM_CANISTER = ITEMS.register("potassium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.POTASSIUM_COMPOUND));
    public static final RegistryObject<Item> CALCIUM_CANISTER = ITEMS.register("calcium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.CALCIUM_COMPOUND));
    public static final RegistryObject<Item> SCANDIUM_CANISTER = ITEMS.register("scandium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.SCANDIUM_COMPOUND));
    public static final RegistryObject<Item> TITANIUM_CANISTER = ITEMS.register("titanium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.TITANIUM_COMPOUND));
    public static final RegistryObject<Item> VANADIUM_CANISTER = ITEMS.register("vanadium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.VANADIUM_COMPOUND));
    public static final RegistryObject<Item> CHROMIUM_CANISTER = ITEMS.register("chromium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.CHROMIUM_COMPOUND));
    public static final RegistryObject<Item> MANGANESE_CANISTER = ITEMS.register("manganese_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.MANGANESE_COMPOUND));
    public static final RegistryObject<Item> IRON_CANISTER = ITEMS.register("iron_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.IRON_COMPOUND));
    public static final RegistryObject<Item> COBALT_CANISTER = ITEMS.register("cobalt_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.COBALT_COMPOUND));
    public static final RegistryObject<Item> NICKEL_CANISTER = ITEMS.register("nickel_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.NICKEL_COMPOUND));
    public static final RegistryObject<Item> COPPER_CANISTER = ITEMS.register("copper_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.COPPER_COMPOUND));
    public static final RegistryObject<Item> ZINC_CANISTER = ITEMS.register("zinc_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.ZINC_COMPOUND));
    public static final RegistryObject<Item> GALLIUM_CANISTER = ITEMS.register("gallium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.GALLIUM_COMPOUND));
    public static final RegistryObject<Item> GERMANIUM_CANISTER = ITEMS.register("germanium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.GERMANIUM_COMPOUND));
    public static final RegistryObject<Item> ARSENIC_CANISTER = ITEMS.register("arsenic_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.ARSENIC_COMPOUND));
    public static final RegistryObject<Item> SELENIUM_CANISTER = ITEMS.register("selenium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.SELENIUM_COMPOUND));
    public static final RegistryObject<Item> BROMINE_CANISTER = ITEMS.register("bromine_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.BROMINE_COMPOUND));
    public static final RegistryObject<Item> KRYPTON_CANISTER = ITEMS.register("krypton_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.KRYPTON_COMPOUND));
    public static final RegistryObject<Item> RUBIDIUM_CANISTER = ITEMS.register("rubidium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.RUBIDIUM_COMPOUND));
    public static final RegistryObject<Item> STRONTIUM_CANISTER = ITEMS.register("strontium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.STRONTIUM_COMPOUND));
    public static final RegistryObject<Item> YTTRIUM_CANISTER = ITEMS.register("yttrium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.YTTRIUM_COMPOUND));
    public static final RegistryObject<Item> ZIRCONIUM_CANISTER = ITEMS.register("zirconium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.ZIRCONIUM_COMPOUND));
    public static final RegistryObject<Item> NIOBIUM_CANISTER = ITEMS.register("niobium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.NIOBIUM_COMPOUND));
    public static final RegistryObject<Item> MOLYBDENUM_CANISTER = ITEMS.register("molybdenum_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.MOLYBDENUM_COMPOUND));
    public static final RegistryObject<Item> TECHNETIUM_CANISTER = ITEMS.register("technetium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.TECHNETIUM_COMPOUND));
    public static final RegistryObject<Item> RUTHENIUM_CANISTER = ITEMS.register("ruthenium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.RUTHENIUM_COMPOUND));
    public static final RegistryObject<Item> RHODIUM_CANISTER = ITEMS.register("rhodium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.RHODIUM_COMPOUND));
    public static final RegistryObject<Item> PALLADIUM_CANISTER = ITEMS.register("palladium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.PALLADIUM_COMPOUND));
    public static final RegistryObject<Item> SILVER_CANISTER = ITEMS.register("silver_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.SILVER_COMPOUND));
    public static final RegistryObject<Item> CADMIUM_CANISTER = ITEMS.register("cadmium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.CADMIUM_COMPOUND));
    public static final RegistryObject<Item> INDIUM_CANISTER = ITEMS.register("indium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.INDIUM_COMPOUND));
    public static final RegistryObject<Item> TIN_CANISTER = ITEMS.register("tin_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.TIN_COMPOUND));
    public static final RegistryObject<Item> ANTIMONY_CANISTER = ITEMS.register("antimony_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.ANTIMONY_COMPOUND));
    public static final RegistryObject<Item> TELLURIUM_CANISTER = ITEMS.register("tellurium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.TELLURIUM_COMPOUND));
    public static final RegistryObject<Item> IODINE_CANISTER = ITEMS.register("iodine_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.IODINE_COMPOUND));
    public static final RegistryObject<Item> XENON_CANISTER = ITEMS.register("xenon_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.XENON_COMPOUND));
    public static final RegistryObject<Item> CESIUM_CANISTER = ITEMS.register("cesium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.CESIUM_COMPOUND));
    public static final RegistryObject<Item> BARIUM_CANISTER = ITEMS.register("barium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.BARIUM_COMPOUND));
    public static final RegistryObject<Item> LANTHANUM_CANISTER = ITEMS.register("lanthanum_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.LANTHANUM_COMPOUND));
    public static final RegistryObject<Item> CERIUM_CANISTER = ITEMS.register("cerium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.CERIUM_COMPOUND));
    public static final RegistryObject<Item> PRASEODYMIUM_CANISTER = ITEMS.register("praseodymium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.PRASEODYMIUM_COMPOUND));
    public static final RegistryObject<Item> NEODYMIUM_CANISTER = ITEMS.register("neodymium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.NEODYMIUM_COMPOUND));
    public static final RegistryObject<Item> PROMETHIUM_CANISTER = ITEMS.register("promethium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.PROMETHIUM_COMPOUND));
    public static final RegistryObject<Item> SAMARIUM_CANISTER = ITEMS.register("samarium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.SAMARIUM_COMPOUND));
    public static final RegistryObject<Item> EUROPIUM_CANISTER = ITEMS.register("europium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.EUROPIUM_COMPOUND));
    public static final RegistryObject<Item> GADOLINIUM_CANISTER = ITEMS.register("gadolinium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.GADOLINIUM_COMPOUND));
    public static final RegistryObject<Item> TERBIUM_CANISTER = ITEMS.register("terbium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.TERBIUM_COMPOUND));
    public static final RegistryObject<Item> DYSPROSIUM_CANISTER = ITEMS.register("dysprosium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.DYSPROSIUM_COMPOUND));
    public static final RegistryObject<Item> HOLMIUM_CANISTER = ITEMS.register("holmium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.HOLMIUM_COMPOUND));
    public static final RegistryObject<Item> ERBIUM_CANISTER = ITEMS.register("erbium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.ERBIUM_COMPOUND));
    public static final RegistryObject<Item> THULIUM_CANISTER = ITEMS.register("thulium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.THULIUM_COMPOUND));
    public static final RegistryObject<Item> YTTERBIUM_CANISTER = ITEMS.register("ytterbium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.YTTERBIUM_COMPOUND));
    public static final RegistryObject<Item> LUTETIUM_CANISTER = ITEMS.register("lutetium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.LUTETIUM_COMPOUND));
    public static final RegistryObject<Item> HAFNIUM_CANISTER = ITEMS.register("hafnium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.HAFNIUM_COMPOUND));
    public static final RegistryObject<Item> TANTALUM_CANISTER = ITEMS.register("tantalum_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.TANTALUM_COMPOUND));
    public static final RegistryObject<Item> TUNGSTEN_CANISTER = ITEMS.register("tungsten_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.TUNGSTEN_COMPOUND));
    public static final RegistryObject<Item> RHENIUM_CANISTER = ITEMS.register("rhenium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.RHENIUM_COMPOUND));
    public static final RegistryObject<Item> OSMIUM_CANISTER = ITEMS.register("osmium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.OSMIUM_COMPOUND));
    public static final RegistryObject<Item> IRIDIUM_CANISTER = ITEMS.register("iridium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.IRIDIUM_COMPOUND));
    public static final RegistryObject<Item> PLATINUM_CANISTER = ITEMS.register("platinum_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.PLATINUM_COMPOUND));
    public static final RegistryObject<Item> GOLD_CANISTER = ITEMS.register("gold_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.GOLD_COMPOUND));
    public static final RegistryObject<Item> MERCURY_CANISTER = ITEMS.register("mercury_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.MERCURY_COMPOUND));
    public static final RegistryObject<Item> THALLIUM_CANISTER = ITEMS.register("thallium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.THALLIUM_COMPOUND));
    public static final RegistryObject<Item> LEAD_CANISTER = ITEMS.register("lead_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.LEAD_COMPOUND));
    public static final RegistryObject<Item> BISMUTH_CANISTER = ITEMS.register("bismuth_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.BISMUTH_COMPOUND));
    public static final RegistryObject<Item> POLONIUM_CANISTER = ITEMS.register("polonium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.POLONIUM_COMPOUND));
    public static final RegistryObject<Item> ASTATINE_CANISTER = ITEMS.register("astatine_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.ASTATINE_COMPOUND));
    public static final RegistryObject<Item> RADON_CANISTER = ITEMS.register("radon_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.RADON_COMPOUND));
    public static final RegistryObject<Item> FRANCIUM_CANISTER = ITEMS.register("francium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.FRANCIUM_COMPOUND));
    public static final RegistryObject<Item> RADIUM_CANISTER = ITEMS.register("radium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.RADIUM_COMPOUND));
    public static final RegistryObject<Item> ACTINIUM_CANISTER = ITEMS.register("actinium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.ACTINIUM_COMPOUND));
    public static final RegistryObject<Item> THORIUM_CANISTER = ITEMS.register("thorium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.THORIUM_COMPOUND));
    public static final RegistryObject<Item> PROTACTINIUM_CANISTER = ITEMS.register("protactinium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.PROTACTINIUM_COMPOUND));
    public static final RegistryObject<Item> URANIUM_CANISTER = ITEMS.register("uranium_canister", () -> new CompoundItem(new Item.Properties(), CompoundItems.URANIUM_COMPOUND));

    public static void register(IEventBus eventBus) {
        ITEMS.register(eventBus);
    }
}
