package gg.hipposgrumm.bmbc;

import com.mojang.logging.LogUtils;
import gg.hipposgrumm.bmbc.blocks.AlloyFurnaceBlock;
import gg.hipposgrumm.bmbc.blocks.AlloyFurnaceBlockEntity;
import gg.hipposgrumm.bmbc.blocks.AlloyFurnaceBlockEntityRenderer;
import gg.hipposgrumm.bmbc.element.Element;
import gg.hipposgrumm.bmbc.element.ElementRegister;
import gg.hipposgrumm.bmbc.gui.AlloyFurnaceMenu;
import gg.hipposgrumm.bmbc.gui.AlloyFurnaceScreen;
import gg.hipposgrumm.bmbc.items.Compound;
import gg.hipposgrumm.bmbc.items.CompoundItem;
import gg.hipposgrumm.bmbc.recipes.AlloySmeltingRecipe;
import net.matty.bmbc.BetterMineBetterCraft;
import net.matty.bmbc.creativemode_tab.*;
import net.minecraft.client.gui.screens.MenuScreens;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.material.Material;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.common.extensions.IForgeMenuType;
import net.minecraftforge.event.CreativeModeTabEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLLoadCompleteEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import org.slf4j.Logger;

import java.util.ArrayList;
import java.util.List;

public class BMBC_Main {
    public static final String MODID = BetterMineBetterCraft.MOD_ID;
    private static final Logger LOGGER = LogUtils.getLogger();

    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, MODID);
    public static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES, MODID);
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, MODID);
    public static final DeferredRegister<MenuType<?>> MENU_TYPES = DeferredRegister.create(ForgeRegistries.MENU_TYPES, MODID);
    public static final DeferredRegister<RecipeSerializer<?>> RECIPE_SERIALIZERS = DeferredRegister.create(ForgeRegistries.RECIPE_SERIALIZERS, MODID);

    // https://www.angelo.edu/faculty/kboudrea/periodic/physical_states.htm
    public static final Element HYDROGEN = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "hydrogen"), "H", 1), -259.14, -252.87);
    public static final Element HELIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "helium"), "He", 2), -272.2, -268.934);
    public static final Element LITHIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "lithium"), "Li", 3), 180.54, 1347);
    public static final Element BERYLLIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "beryllium"), "Be", 4), 1278, 2970);
    public static final Element BORON = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "boron"), "B", 5), 2300, 3658);
    public static final Element CARBON = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "carbon"), "C", 6), 3527, 4827);
    public static final Element NITROGEN = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "nitrogen"), "N", 7), -209.86, -195.8);
    public static final Element OXYGEN = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "oxygen"), "O", 8), -218.4, -182.96);
    public static final Element FLUORINE = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "fluorine"), "F", 9), -219.62, -118.14);
    public static final Element NEON = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "neon"), "Ne", 10), -248.67, -246.05);
    public static final Element SODIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "sodium"), "Na", 11), 97.81, 882.9);
    public static final Element MAGNESIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "magnesium"), "Mg", 12), 648.8, 1090);
    public static final Element ALUMINIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "aluminium"), "Al", 13), 660.37, 2467);
    public static final Element SILICON = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "silicon"), "Si", 14), 1410, 2355);
    public static final Element PHOSPHORUS = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "phosphorus"), "P", 15), 44.1, 280);
    public static final Element SULFUR = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "sulfur"), "S", 16), 130, 444.67);
    public static final Element CHLORINE = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "chlorine"), "Cl", 17), -100.98, -33.97);
    public static final Element ARGON = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "argon"), "Ar", 18), -189.37, -185.86);
    public static final Element POTASSIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "potassium"), "K", 19), 63.65, 774);
    public static final Element CALCIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "calcium"), "Ca", 20), 839, 1484);
    public static final Element SCANDIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "scandium"), "Sc", 21), 1541, 2831);
    public static final Element TITANIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "titanium"), "Ti", 22), 1660, 3287);
    public static final Element VANADIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "vanadium"), "V", 23), 1887, 3377);
    public static final Element CHROMIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "chromium"), "Cr", 24), 1857, 2672);
    public static final Element MANGANESE = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "manganese"), "Mn", 25), 1244, 1962);
    public static final Element IRON = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "iron"), "Fe", 26), 1535, 2750); // apart from the element...
    public static final Element COBALT = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "cobalt"), "Co", 27), 1495, 2870);
    public static final Element NICKEL = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "nickel"), "Ni", 28), 1453, 2732);
    public static final Element COPPER = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "copper"), "Cu", 29), 1083.4, 2567);
    public static final Element ZINC = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "zinc"), "Zn", 30), 419.58, 907);
    public static final Element GALLIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "gallium"), "Ga", 31), 29.78, 2403);
    public static final Element GERMANIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "germanium"), "Ge", 32), 937.4, 2830);
    public static final Element ARSENIC = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "arsenic"), "As", 33), 817, 817.0000001);
    public static final Element SELENIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "selenium"), "Se", 34), 217, 684.9);
    public static final Element BROMINE = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "bromine"), "Br", 35), -7.3, 58.78);
    public static final Element KRYPTON = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "krypton"), "Kr", 36), -156.6, -152.3);
    public static final Element RUBIDIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "rubidium"), "Rb", 37), 39, 688);
    public static final Element STRONTIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "strontium"), "Sr", 38), 769, 1384);
    public static final Element YTTRIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "yttrium"), "Y", 39), 1522, 3338);
    public static final Element ZIRCONIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "zirconium"), "Zr", 40), 1852, 4377);
    public static final Element NIOBIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "niobium"), "Nb", 41), 2468, 4742);
    public static final Element MOLYBDENUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "molybdenum"), "Mo", 42), 2617, 4612);
    public static final Element TECHNETIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "technetium"), "Tc", 43), 2172, 4877);
    public static final Element RUTHENIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "ruthenium"), "Ru", 44), 2310, 3900);
    public static final Element RHODIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "rhodium"), "Rh", 45), 1966, 3727);
    public static final Element PALLADIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "palladium"), "Pd", 46), 1552, 3140);
    public static final Element SILVER = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "silver"), "Ag", 47), 961.93, 2212);
    public static final Element CADMIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "cadmium"), "Cd", 48), 320.9, 765);
    public static final Element INDIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "indium"), "In", 49), 156.17, 2080);
    public static final Element TIN = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "tin"), "Sn", 50), 231.97, 2270);
    public static final Element ANTIMONY = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "antimony"), "Sb", 51), 640.74, 1635);
    public static final Element TELLURIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "tellurium"), "Te", 52), 449.5, 989.8);
    public static final Element IODINE = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "iodine"), "I", 53), 113.5, 184.35);
    public static final Element XENON = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "xenon"), "Xe", 54), -111.9, -107.1);
    public static final Element CESIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "cesium"), "Cs", 55), 28.4, 678.4);
    public static final Element BARIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "barium"), "Ba", 56), 729, 1637);
    public static final Element LANTHANUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "lanthanum"), "La", 57), 921, 3457);
    public static final Element CERIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "cerium"), "Ce", 58), 799, 3426);
    public static final Element PRASEODYMIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "praseodymium"), "Pr", 59), 931, 3512);
    public static final Element NEODYMIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "neodymium"), "Nd", 60), 1021, 3068);
    public static final Element PROMETHIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "promethium"), "Pm", 61), 1168, 2727);
    public static final Element SAMARIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "samarium"), "Sm", 62), 1077, 1791);
    public static final Element EUROPIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "europium"), "Eu", 63), 882, 1597);
    public static final Element GADOLINIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "gadolinium"), "Gd", 64), 1313, 3266);
    public static final Element TERBIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "terbium"), "Tb", 65), 1356, 3123);
    public static final Element DYSPROSIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "dysprosium"), "Dy", 66), 1412, 2563);
    public static final Element HOLMIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "holmium"), "Ho", 67), 1474, 2695);
    public static final Element ERBIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "erbium"), "Er", 68), 1529, 2863);
    public static final Element THULIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "thulium"), "Tm", 69), 1545, 1947);
    public static final Element YTTERBIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "ytterbium"), "Yb", 70), 824, 1193);
    public static final Element LUTETIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "lutetium"), "Lu", 71), 1663, 3395);
    public static final Element HAFNIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "hafnium"), "Hf", 72), 2230, 5197);
    public static final Element TANTALUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "tantalum"), "Ta", 73), 2996, 5425);
    public static final Element TUNGSTEN = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "tungsten"), "W", 74), 3407, 5657);
    public static final Element RHENIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "rhenium"), "Re", 75), 3180, 5627);
    public static final Element OSMIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "osmium"), "Os", 76), 3054, 5027);
    public static final Element IRIDIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "iridium"), "Ir", 77), 2410, 4130);
    public static final Element PLATINUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "platinum"), "Pt", 78), 1772, 3827);
    public static final Element GOLD = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "gold"), "Au", 79), 1064.43, 2807);
    public static final Element MERCURY = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "mercury"), "Hg", 80), -38.87, 356.58);
    public static final Element THALLIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "thallium"), "Tl", 81), 303.5, 1457);
    public static final Element LEAD = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "lead"), "Pb", 82), 327.5, 1740);
    public static final Element BISMUTH = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "bismuth"), "Bi", 83), 271.3, 1610);
    public static final Element POLONIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "polonium"), "Po", 84), 254, 962);
    public static final Element ASTATINE = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "astatine"), "At", 85), 302, 337);
    public static final Element RADON = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "radon"), "Rn", 86), -71, -61.8);
    public static final Element FRANCIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "francium"), "Fr", 87), 27, 677);
    public static final Element RADIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "radium"), "Ra", 88), 700, 1140);
    public static final Element ACTINIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "actinium"), "Ac", 89), 1047, 3197);
    public static final Element THORIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "thorium"), "Th", 90), 1750, 4787);
    public static final Element PROTACTINIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "protactinium"), "Pa", 91), 1840, 4027);
    public static final Element URANIUM = ElementRegister.registerElement(new Element.Data(new ResourceLocation(MODID, "uranium"), "U", 92), 1132.3, 3745);

    // All Generic Compounds
    // Solid
    public static final Compound HYDROGEN_COMPOUND = new Compound(HYDROGEN);
    public static final Compound HELIUM_COMPOUND = new Compound(HELIUM);
    public static final Compound LITHIUM_COMPOUND = new Compound(LITHIUM);
    public static final Compound BERYLLIUM_COMPOUND = new Compound(BERYLLIUM);
    public static final Compound BORON_COMPOUND = new Compound(BORON);
    public static final Compound CARBON_COMPOUND = new Compound(CARBON);
    public static final Compound NITROGEN_COMPOUND = new Compound(NITROGEN);
    public static final Compound OXYGEN_COMPOUND = new Compound(OXYGEN);
    public static final Compound FLUORINE_COMPOUND = new Compound(FLUORINE);
    public static final Compound NEON_COMPOUND = new Compound(NEON);
    public static final Compound SODIUM_COMPOUND = new Compound(SODIUM);
    public static final Compound MAGNESIUM_COMPOUND = new Compound(MAGNESIUM);
    public static final Compound ALUMINIUM_COMPOUND = new Compound(ALUMINIUM);
    public static final Compound SILICON_COMPOUND = new Compound(SILICON);
    public static final Compound PHOSPHORUS_COMPOUND = new Compound(PHOSPHORUS);
    public static final Compound SULFUR_COMPOUND = new Compound(SULFUR);
    public static final Compound CHLORINE_COMPOUND = new Compound(CHLORINE);
    public static final Compound ARGON_COMPOUND = new Compound(ARGON);
    public static final Compound POTASSIUM_COMPOUND = new Compound(POTASSIUM);
    public static final Compound CALCIUM_COMPOUND = new Compound(CALCIUM);
    public static final Compound SCANDIUM_COMPOUND = new Compound(SCANDIUM);
    public static final Compound TITANIUM_COMPOUND = new Compound(TITANIUM);
    public static final Compound VANADIUM_COMPOUND = new Compound(VANADIUM);
    public static final Compound CHROMIUM_COMPOUND = new Compound(CHROMIUM);
    public static final Compound MANGANESE_COMPOUND = new Compound(MANGANESE);
    public static final Compound IRON_COMPOUND = new Compound(IRON);
    public static final Compound COBALT_COMPOUND = new Compound(COBALT);
    public static final Compound NICKEL_COMPOUND = new Compound(NICKEL);
    public static final Compound COPPER_COMPOUND = new Compound(COPPER);
    public static final Compound ZINC_COMPOUND = new Compound(ZINC);
    public static final Compound GALLIUM_COMPOUND = new Compound(GALLIUM);
    public static final Compound GERMANIUM_COMPOUND = new Compound(GERMANIUM);
    public static final Compound ARSENIC_COMPOUND = new Compound(ARSENIC);
    public static final Compound SELENIUM_COMPOUND = new Compound(SELENIUM);
    public static final Compound BROMINE_COMPOUND = new Compound(BROMINE);
    public static final Compound KRYPTON_COMPOUND = new Compound(KRYPTON);
    public static final Compound RUBIDIUM_COMPOUND = new Compound(RUBIDIUM);
    public static final Compound STRONTIUM_COMPOUND = new Compound(STRONTIUM);
    public static final Compound YTTRIUM_COMPOUND = new Compound(YTTRIUM);
    public static final Compound ZIRCONIUM_COMPOUND = new Compound(ZIRCONIUM);
    public static final Compound NIOBIUM_COMPOUND = new Compound(NIOBIUM);
    public static final Compound MOLYBDENUM_COMPOUND = new Compound(MOLYBDENUM);
    public static final Compound TECHNETIUM_COMPOUND = new Compound(TECHNETIUM);
    public static final Compound RUTHENIUM_COMPOUND = new Compound(RUTHENIUM);
    public static final Compound RHODIUM_COMPOUND = new Compound(RHODIUM);
    public static final Compound PALLADIUM_COMPOUND = new Compound(PALLADIUM);
    public static final Compound SILVER_COMPOUND = new Compound(SILVER);
    public static final Compound CADMIUM_COMPOUND = new Compound(CADMIUM);
    public static final Compound INDIUM_COMPOUND = new Compound(INDIUM);
    public static final Compound TIN_COMPOUND = new Compound(TIN);
    public static final Compound ANTIMONY_COMPOUND = new Compound(ANTIMONY);
    public static final Compound TELLURIUM_COMPOUND = new Compound(TELLURIUM);
    public static final Compound IODINE_COMPOUND = new Compound(IODINE);
    public static final Compound XENON_COMPOUND = new Compound(XENON);
    public static final Compound CESIUM_COMPOUND = new Compound(CESIUM);
    public static final Compound BARIUM_COMPOUND = new Compound(BARIUM);
    public static final Compound LANTHANUM_COMPOUND = new Compound(LANTHANUM);
    public static final Compound CERIUM_COMPOUND = new Compound(CERIUM);
    public static final Compound PRASEODYMIUM_COMPOUND = new Compound(PRASEODYMIUM);
    public static final Compound NEODYMIUM_COMPOUND = new Compound(NEODYMIUM);
    public static final Compound PROMETHIUM_COMPOUND = new Compound(PROMETHIUM);
    public static final Compound SAMARIUM_COMPOUND = new Compound(SAMARIUM);
    public static final Compound EUROPIUM_COMPOUND = new Compound(EUROPIUM);
    public static final Compound GADOLINIUM_COMPOUND = new Compound(GADOLINIUM);
    public static final Compound TERBIUM_COMPOUND = new Compound(TERBIUM);
    public static final Compound DYSPROSIUM_COMPOUND = new Compound(DYSPROSIUM);
    public static final Compound HOLMIUM_COMPOUND = new Compound(HOLMIUM);
    public static final Compound ERBIUM_COMPOUND = new Compound(ERBIUM);
    public static final Compound THULIUM_COMPOUND = new Compound(THULIUM);
    public static final Compound YTTERBIUM_COMPOUND = new Compound(YTTERBIUM);
    public static final Compound LUTETIUM_COMPOUND = new Compound(LUTETIUM);
    public static final Compound HAFNIUM_COMPOUND = new Compound(HAFNIUM);
    public static final Compound TANTALUM_COMPOUND = new Compound(TANTALUM);
    public static final Compound TUNGSTEN_COMPOUND = new Compound(TUNGSTEN);
    public static final Compound RHENIUM_COMPOUND = new Compound(RHENIUM);
    public static final Compound OSMIUM_COMPOUND = new Compound(OSMIUM);
    public static final Compound IRIDIUM_COMPOUND = new Compound(IRIDIUM);
    public static final Compound PLATINUM_COMPOUND = new Compound(PLATINUM);
    public static final Compound GOLD_COMPOUND = new Compound(GOLD);
    public static final Compound MERCURY_COMPOUND = new Compound(MERCURY);
    public static final Compound THALLIUM_COMPOUND = new Compound(THALLIUM);
    public static final Compound LEAD_COMPOUND = new Compound(LEAD);
    public static final Compound BISMUTH_COMPOUND = new Compound(BISMUTH);
    public static final Compound POLONIUM_COMPOUND = new Compound(POLONIUM);
    public static final Compound ASTATINE_COMPOUND = new Compound(ASTATINE);
    public static final Compound RADON_COMPOUND = new Compound(RADON);
    public static final Compound FRANCIUM_COMPOUND = new Compound(FRANCIUM);
    public static final Compound RADIUM_COMPOUND = new Compound(RADIUM);
    public static final Compound ACTINIUM_COMPOUND = new Compound(ACTINIUM);
    public static final Compound THORIUM_COMPOUND = new Compound(THORIUM);
    public static final Compound PROTACTINIUM_COMPOUND = new Compound(PROTACTINIUM);
    public static final Compound URANIUM_COMPOUND = new Compound(URANIUM);

    // Solid
     public static final RegistryObject<Item> HYDROGEN_INGOT = ITEMS.register("hydrogen_ingot", () -> new CompoundItem(new Item.Properties(), HYDROGEN_COMPOUND));
     public static final RegistryObject<Item> HELIUM_INGOT = ITEMS.register("helium_ingot", () -> new CompoundItem(new Item.Properties(), HELIUM_COMPOUND));
    public static final RegistryObject<Item> LITHIUM_INGOT = ITEMS.register("lithium_ingot", () -> new CompoundItem(new Item.Properties(), LITHIUM_COMPOUND));
    public static final RegistryObject<Item> BERYLLIUM_INGOT = ITEMS.register("beryllium_ingot", () -> new CompoundItem(new Item.Properties(), BERYLLIUM_COMPOUND));
    public static final RegistryObject<Item> BORON_INGOT = ITEMS.register("boron_ingot", () -> new CompoundItem(new Item.Properties(), BORON_COMPOUND));
    public static final RegistryObject<Item> CARBON_INGOT = ITEMS.register("carbon_ingot", () -> new CompoundItem(new Item.Properties(), CARBON_COMPOUND));
     public static final RegistryObject<Item> NITROGEN_INGOT = ITEMS.register("nitrogen_ingot", () -> new CompoundItem(new Item.Properties(), NITROGEN_COMPOUND));
     public static final RegistryObject<Item> OXYGEN_INGOT = ITEMS.register("oxygen_ingot", () -> new CompoundItem(new Item.Properties(), OXYGEN_COMPOUND));
     public static final RegistryObject<Item> FLUORINE_INGOT = ITEMS.register("fluorine_ingot", () -> new CompoundItem(new Item.Properties(), FLUORINE_COMPOUND));
     public static final RegistryObject<Item> NEON_INGOT = ITEMS.register("neon_ingot", () -> new CompoundItem(new Item.Properties(), NEON_COMPOUND));
    public static final RegistryObject<Item> SODIUM_INGOT = ITEMS.register("sodium_ingot", () -> new CompoundItem(new Item.Properties(), SODIUM_COMPOUND));
    public static final RegistryObject<Item> MAGNESIUM_INGOT = ITEMS.register("magnesium_ingot", () -> new CompoundItem(new Item.Properties(), MAGNESIUM_COMPOUND));
    public static final RegistryObject<Item> ALUMINIUM_INGOT = ITEMS.register("aluminium_ingot", () -> new CompoundItem(new Item.Properties(), ALUMINIUM_COMPOUND));
    public static final RegistryObject<Item> SILICON_CRYSTAL = ITEMS.register("silicon_crystal", () -> new CompoundItem(new Item.Properties(), SILICON_COMPOUND));
    public static final RegistryObject<Item> WHITE_PHOSPHORUS = ITEMS.register("white_phosphorus", () -> new CompoundItem(new Item.Properties(), PHOSPHORUS_COMPOUND));
    public static final RegistryObject<Item> RED_PHOSPHORUS = ITEMS.register("red_phosphorus", () -> new CompoundItem(new Item.Properties(), PHOSPHORUS_COMPOUND));
    public static final RegistryObject<Item> BLACK_PHOSPHORUS = ITEMS.register("black_phosphorus", () -> new CompoundItem(new Item.Properties(), PHOSPHORUS_COMPOUND));
    public static final RegistryObject<Item> SULFUR_CRYSTAL = ITEMS.register("sulfur_crystal", () -> new CompoundItem(new Item.Properties(), SULFUR_COMPOUND));
     public static final RegistryObject<Item> CHLORINE_INGOT = ITEMS.register("chlorine_ingot", () -> new CompoundItem(new Item.Properties(), CHLORINE_COMPOUND));
     public static final RegistryObject<Item> ARGON_INGOT = ITEMS.register("argon_ingot", () -> new CompoundItem(new Item.Properties(), ARGON_COMPOUND));
    public static final RegistryObject<Item> POTASSIUM_INGOT = ITEMS.register("potassium_ingot", () -> new CompoundItem(new Item.Properties(), POTASSIUM_COMPOUND));
    public static final RegistryObject<Item> CALCIUM_ROCK = ITEMS.register("calcium_rock", () -> new CompoundItem(new Item.Properties(), CALCIUM_COMPOUND));
    public static final RegistryObject<Item> SCANDIUM_INGOT = ITEMS.register("scandium_ingot", () -> new CompoundItem(new Item.Properties(), SCANDIUM_COMPOUND));
    public static final RegistryObject<Item> TITANIUM_INGOT = ITEMS.register("titanium_ingot", () -> new CompoundItem(new Item.Properties(), TITANIUM_COMPOUND));
    public static final RegistryObject<Item> VANADIUM_INGOT = ITEMS.register("vanadium_ingot", () -> new CompoundItem(new Item.Properties(), VANADIUM_COMPOUND));
    public static final RegistryObject<Item> CHROMIUM_CRYSTAL = ITEMS.register("chromium_crystal", () -> new CompoundItem(new Item.Properties(), CHROMIUM_COMPOUND));
    public static final RegistryObject<Item> MANGANESE_INGOT = ITEMS.register("manganese_ingot", () -> new CompoundItem(new Item.Properties(), MANGANESE_COMPOUND));
    //public static final RegistryObject<Item> IRON_INGOT = ITEMS.register("iron_ingot", () -> new CompoundItem(new Item.Properties(), IRON_COMPOUND));
    public static final RegistryObject<Item> COBALT_INGOT = ITEMS.register("cobalt_ingot", () -> new CompoundItem(new Item.Properties(), COBALT_COMPOUND));
    public static final RegistryObject<Item> NICKEL_INGOT = ITEMS.register("nickel_ingot", () -> new CompoundItem(new Item.Properties(), NICKEL_COMPOUND));
    //public static final RegistryObject<Item> COPPER_INGOT = ITEMS.register("copper_ingot", () -> new CompoundItem(new Item.Properties(), COPPER_COMPOUND));
    public static final RegistryObject<Item> ZINC_INGOT = ITEMS.register("zinc_ingot", () -> new CompoundItem(new Item.Properties(), ZINC_COMPOUND));
    public static final RegistryObject<Item> GALLIUM_INGOT = ITEMS.register("gallium_ingot", () -> new CompoundItem(new Item.Properties(), GALLIUM_COMPOUND));
    public static final RegistryObject<Item> GERMANIUM_INGOT = ITEMS.register("germanium_ingot", () -> new CompoundItem(new Item.Properties(), GERMANIUM_COMPOUND));
    public static final RegistryObject<Item> ARSENIC_INGOT = ITEMS.register("arsenic_ingot", () -> new CompoundItem(new Item.Properties(), ARSENIC_COMPOUND));
    public static final RegistryObject<Item> SELENIUM_INGOT = ITEMS.register("selenium_ingot", () -> new CompoundItem(new Item.Properties(), SELENIUM_COMPOUND));
     public static final RegistryObject<Item> BROMINE_INGOT = ITEMS.register("bromine_ingot", () -> new CompoundItem(new Item.Properties(), BROMINE_COMPOUND));
     public static final RegistryObject<Item> KRYPTON_INGOT = ITEMS.register("krypton_ingot", () -> new CompoundItem(new Item.Properties(), KRYPTON_COMPOUND));
    public static final RegistryObject<Item> RUBIDIUM_INGOT = ITEMS.register("rubidium_ingot", () -> new CompoundItem(new Item.Properties(), RUBIDIUM_COMPOUND));
    public static final RegistryObject<Item> STRONTIUM_INGOT = ITEMS.register("strontium_ingot", () -> new CompoundItem(new Item.Properties(), STRONTIUM_COMPOUND));
    public static final RegistryObject<Item> YTTRIUM_INGOT = ITEMS.register("yttrium_ingot", () -> new CompoundItem(new Item.Properties(), YTTRIUM_COMPOUND));
    public static final RegistryObject<Item> ZIRCONIUM_INGOT = ITEMS.register("zirconium_ingot", () -> new CompoundItem(new Item.Properties(), ZIRCONIUM_COMPOUND));
    public static final RegistryObject<Item> NIOBIUM_INGOT = ITEMS.register("niobium_ingot", () -> new CompoundItem(new Item.Properties(), NIOBIUM_COMPOUND));
    public static final RegistryObject<Item> MOLYBDENUM_INGOT = ITEMS.register("molybdenum_ingot", () -> new CompoundItem(new Item.Properties(), MOLYBDENUM_COMPOUND));
    public static final RegistryObject<Item> TECHNETIUM_INGOT = ITEMS.register("technetium_ingot", () -> new CompoundItem(new Item.Properties(), TECHNETIUM_COMPOUND));
    public static final RegistryObject<Item> RUTHENIUM_INGOT = ITEMS.register("ruthenium_ingot", () -> new CompoundItem(new Item.Properties(), RUTHENIUM_COMPOUND));
    public static final RegistryObject<Item> RHODIUM_INGOT = ITEMS.register("rhodium_ingot", () -> new CompoundItem(new Item.Properties(), RHODIUM_COMPOUND));
    public static final RegistryObject<Item> PALLADIUM_INGOT = ITEMS.register("palladium_ingot", () -> new CompoundItem(new Item.Properties(), PALLADIUM_COMPOUND));
    public static final RegistryObject<Item> SILVER_INGOT = ITEMS.register("silver_ingot", () -> new CompoundItem(new Item.Properties(), SILVER_COMPOUND));
    public static final RegistryObject<Item> CADMIUM_INGOT = ITEMS.register("cadmium_ingot", () -> new CompoundItem(new Item.Properties(), CADMIUM_COMPOUND));
    public static final RegistryObject<Item> INDIUM_INGOT = ITEMS.register("indium_ingot", () -> new CompoundItem(new Item.Properties(), INDIUM_COMPOUND));
    public static final RegistryObject<Item> TIN_INGOT = ITEMS.register("tin_ingot", () -> new CompoundItem(new Item.Properties(), TIN_COMPOUND));
    public static final RegistryObject<Item> ANTIMONY_INGOT = ITEMS.register("antimony_ingot", () -> new CompoundItem(new Item.Properties(), ANTIMONY_COMPOUND));
    public static final RegistryObject<Item> TELLURIUM_INGOT = ITEMS.register("tellurium_ingot", () -> new CompoundItem(new Item.Properties(), TELLURIUM_COMPOUND));
    public static final RegistryObject<Item> IODINE_INGOT = ITEMS.register("iodine_ingot", () -> new CompoundItem(new Item.Properties(), IODINE_COMPOUND));
     public static final RegistryObject<Item> XENON_INGOT = ITEMS.register("xenon_ingot", () -> new CompoundItem(new Item.Properties(), XENON_COMPOUND));
    public static final RegistryObject<Item> CESIUM_INGOT = ITEMS.register("cesium_ingot", () -> new CompoundItem(new Item.Properties(), CESIUM_COMPOUND));
    public static final RegistryObject<Item> BARIUM_INGOT = ITEMS.register("barium_ingot", () -> new CompoundItem(new Item.Properties(), BARIUM_COMPOUND));
    public static final RegistryObject<Item> LANTHANUM_INGOT = ITEMS.register("lanthanum_ingot", () -> new CompoundItem(new Item.Properties(), LANTHANUM_COMPOUND));
    public static final RegistryObject<Item> CERIUM_INGOT = ITEMS.register("cerium_ingot", () -> new CompoundItem(new Item.Properties(), CERIUM_COMPOUND));
    public static final RegistryObject<Item> PRASEODYMIUM_INGOT = ITEMS.register("praseodymium_ingot", () -> new CompoundItem(new Item.Properties(), PRASEODYMIUM_COMPOUND));
    public static final RegistryObject<Item> NEODYMIUM_INGOT = ITEMS.register("neodymium_ingot", () -> new CompoundItem(new Item.Properties(), NEODYMIUM_COMPOUND));
    public static final RegistryObject<Item> PROMETHIUM_INGOT = ITEMS.register("promethium_ingot", () -> new CompoundItem(new Item.Properties(), PROMETHIUM_COMPOUND));
    public static final RegistryObject<Item> SAMARIUM_INGOT = ITEMS.register("samarium_ingot", () -> new CompoundItem(new Item.Properties(), SAMARIUM_COMPOUND));
    public static final RegistryObject<Item> EUROPIUM_INGOT = ITEMS.register("europium_ingot", () -> new CompoundItem(new Item.Properties(), EUROPIUM_COMPOUND));
    public static final RegistryObject<Item> GADOLINIUM_INGOT = ITEMS.register("gadolinium_ingot", () -> new CompoundItem(new Item.Properties(), GADOLINIUM_COMPOUND));
    public static final RegistryObject<Item> TERBIUM_INGOT = ITEMS.register("terbium_ingot", () -> new CompoundItem(new Item.Properties(), TERBIUM_COMPOUND));
    public static final RegistryObject<Item> DYSPROSIUM_INGOT = ITEMS.register("dysprosium_ingot", () -> new CompoundItem(new Item.Properties(), DYSPROSIUM_COMPOUND));
    public static final RegistryObject<Item> HOLMIUM_INGOT = ITEMS.register("holmium_ingot", () -> new CompoundItem(new Item.Properties(), HOLMIUM_COMPOUND));
    public static final RegistryObject<Item> ERBIUM_INGOT = ITEMS.register("erbium_ingot", () -> new CompoundItem(new Item.Properties(), ERBIUM_COMPOUND));
    public static final RegistryObject<Item> THULIUM_INGOT = ITEMS.register("thulium_ingot", () -> new CompoundItem(new Item.Properties(), THULIUM_COMPOUND));
    public static final RegistryObject<Item> YTTERBIUM_INGOT = ITEMS.register("ytterbium_ingot", () -> new CompoundItem(new Item.Properties(), YTTERBIUM_COMPOUND));
    public static final RegistryObject<Item> LUTETIUM_INGOT = ITEMS.register("lutetium_ingot", () -> new CompoundItem(new Item.Properties(), LUTETIUM_COMPOUND));
    public static final RegistryObject<Item> HAFNIUM_INGOT = ITEMS.register("hafnium_ingot", () -> new CompoundItem(new Item.Properties(), HAFNIUM_COMPOUND));
    public static final RegistryObject<Item> TANTALUM_INGOT = ITEMS.register("tantalum_ingot", () -> new CompoundItem(new Item.Properties(), TANTALUM_COMPOUND));
    public static final RegistryObject<Item> TUNGSTEN_INGOT = ITEMS.register("tungsten_ingot", () -> new CompoundItem(new Item.Properties(), TUNGSTEN_COMPOUND));
    public static final RegistryObject<Item> RHENIUM_INGOT = ITEMS.register("rhenium_ingot", () -> new CompoundItem(new Item.Properties(), RHENIUM_COMPOUND));
    public static final RegistryObject<Item> OSMIUM_INGOT = ITEMS.register("osmium_ingot", () -> new CompoundItem(new Item.Properties(), OSMIUM_COMPOUND));
    public static final RegistryObject<Item> IRIDIUM_INGOT = ITEMS.register("iridium_ingot", () -> new CompoundItem(new Item.Properties(), IRIDIUM_COMPOUND));
    public static final RegistryObject<Item> PLATINUM_INGOT = ITEMS.register("platinum_ingot", () -> new CompoundItem(new Item.Properties(), PLATINUM_COMPOUND));
    //public static final RegistryObject<Item> GOLD_INGOT = ITEMS.register("gold_ingot", () -> new CompoundItem(new Item.Properties(), GOLD_COMPOUND));
    public static final RegistryObject<Item> MERCURY_INGOT = ITEMS.register("mercury_ingot", () -> new CompoundItem(new Item.Properties(), MERCURY_COMPOUND));
    public static final RegistryObject<Item> THALLIUM_INGOT = ITEMS.register("thallium_ingot", () -> new CompoundItem(new Item.Properties(), THALLIUM_COMPOUND));
    public static final RegistryObject<Item> LEAD_INGOT = ITEMS.register("lead_ingot", () -> new CompoundItem(new Item.Properties(), LEAD_COMPOUND));
    public static final RegistryObject<Item> BISMUTH_INGOT = ITEMS.register("bismuth_ingot", () -> new CompoundItem(new Item.Properties(), BISMUTH_COMPOUND));
    public static final RegistryObject<Item> POLONIUM_INGOT = ITEMS.register("polonium_ingot", () -> new CompoundItem(new Item.Properties(), POLONIUM_COMPOUND));
    public static final RegistryObject<Item> ASTATINE_INGOT = ITEMS.register("astatine_ingot", () -> new CompoundItem(new Item.Properties(), ASTATINE_COMPOUND));
     public static final RegistryObject<Item> RADON_INGOT = ITEMS.register("radon_ingot", () -> new CompoundItem(new Item.Properties(), RADON_COMPOUND));
    public static final RegistryObject<Item> FRANCIUM_INGOT = ITEMS.register("francium_ingot", () -> new CompoundItem(new Item.Properties(), FRANCIUM_COMPOUND));
    public static final RegistryObject<Item> RADIUM_INGOT = ITEMS.register("radium_ingot", () -> new CompoundItem(new Item.Properties(), RADIUM_COMPOUND));
    public static final RegistryObject<Item> ACTINIUM_INGOT = ITEMS.register("actinium_ingot", () -> new CompoundItem(new Item.Properties(), ACTINIUM_COMPOUND));
    public static final RegistryObject<Item> THORIUM_INGOT = ITEMS.register("thorium_ingot", () -> new CompoundItem(new Item.Properties(), THORIUM_COMPOUND));
    public static final RegistryObject<Item> PROTACTINIUM_INGOT = ITEMS.register("protactinium_ingot", () -> new CompoundItem(new Item.Properties(), PROTACTINIUM_COMPOUND));
    public static final RegistryObject<Item> URANIUM_INGOT = ITEMS.register("uranium_ingot", () -> new CompoundItem(new Item.Properties(), URANIUM_COMPOUND));

    // Liquid
    public static final RegistryObject<Item> HYDROGEN_CANISTER = ITEMS.register("hydrogen_canister", () -> new CompoundItem(new Item.Properties(), HYDROGEN_COMPOUND));
    public static final RegistryObject<Item> HELIUM_CANISTER = ITEMS.register("helium_canister", () -> new CompoundItem(new Item.Properties(), HELIUM_COMPOUND));
    public static final RegistryObject<Item> LITHIUM_CANISTER = ITEMS.register("lithium_canister", () -> new CompoundItem(new Item.Properties(), LITHIUM_COMPOUND));
    public static final RegistryObject<Item> BERYLLIUM_CANISTER = ITEMS.register("beryllium_canister", () -> new CompoundItem(new Item.Properties(), BERYLLIUM_COMPOUND));
    public static final RegistryObject<Item> BORON_CANISTER = ITEMS.register("boron_canister", () -> new CompoundItem(new Item.Properties(), BORON_COMPOUND));
    public static final RegistryObject<Item> CARBON_CANISTER = ITEMS.register("carbon_canister", () -> new CompoundItem(new Item.Properties(), CARBON_COMPOUND));
    public static final RegistryObject<Item> NITROGEN_CANISTER = ITEMS.register("nitrogen_canister", () -> new CompoundItem(new Item.Properties(), NITROGEN_COMPOUND));
    public static final RegistryObject<Item> OXYGEN_CANISTER = ITEMS.register("oxygen_canister", () -> new CompoundItem(new Item.Properties(), OXYGEN_COMPOUND));
    public static final RegistryObject<Item> FLUORINE_CANISTER = ITEMS.register("fluorine_canister", () -> new CompoundItem(new Item.Properties(), FLUORINE_COMPOUND));
    public static final RegistryObject<Item> NEON_CANISTER = ITEMS.register("neon_canister", () -> new CompoundItem(new Item.Properties(), NEON_COMPOUND));
    public static final RegistryObject<Item> SODIUM_CANISTER = ITEMS.register("sodium_canister", () -> new CompoundItem(new Item.Properties(), SODIUM_COMPOUND));
    public static final RegistryObject<Item> MAGNESIUM_CANISTER = ITEMS.register("magnesium_canister", () -> new CompoundItem(new Item.Properties(), MAGNESIUM_COMPOUND));
    public static final RegistryObject<Item> ALUMINIUM_CANISTER = ITEMS.register("aluminium_canister", () -> new CompoundItem(new Item.Properties(), ALUMINIUM_COMPOUND));
    public static final RegistryObject<Item> SILICON_CANISTER = ITEMS.register("silicon_canister", () -> new CompoundItem(new Item.Properties(), SILICON_COMPOUND));
    public static final RegistryObject<Item> PHOSPHORUS_CANISTER = ITEMS.register("phosphorus_canister", () -> new CompoundItem(new Item.Properties(), PHOSPHORUS_COMPOUND));
    public static final RegistryObject<Item> SULFUR_CANISTER = ITEMS.register("sulfur_canister", () -> new CompoundItem(new Item.Properties(), SULFUR_COMPOUND));
    public static final RegistryObject<Item> CHLORINE_CANISTER = ITEMS.register("chlorine_canister", () -> new CompoundItem(new Item.Properties(), CHLORINE_COMPOUND));
    public static final RegistryObject<Item> ARGON_CANISTER = ITEMS.register("argon_canister", () -> new CompoundItem(new Item.Properties(), ARGON_COMPOUND));
    public static final RegistryObject<Item> POTASSIUM_CANISTER = ITEMS.register("potassium_canister", () -> new CompoundItem(new Item.Properties(), POTASSIUM_COMPOUND));
    public static final RegistryObject<Item> CALCIUM_CANISTER = ITEMS.register("calcium_canister", () -> new CompoundItem(new Item.Properties(), CALCIUM_COMPOUND));
    public static final RegistryObject<Item> SCANDIUM_CANISTER = ITEMS.register("scandium_canister", () -> new CompoundItem(new Item.Properties(), SCANDIUM_COMPOUND));
    public static final RegistryObject<Item> TITANIUM_CANISTER = ITEMS.register("titanium_canister", () -> new CompoundItem(new Item.Properties(), TITANIUM_COMPOUND));
    public static final RegistryObject<Item> VANADIUM_CANISTER = ITEMS.register("vanadium_canister", () -> new CompoundItem(new Item.Properties(), VANADIUM_COMPOUND));
    public static final RegistryObject<Item> CHROMIUM_CANISTER = ITEMS.register("chromium_canister", () -> new CompoundItem(new Item.Properties(), CHROMIUM_COMPOUND));
    public static final RegistryObject<Item> MANGANESE_CANISTER = ITEMS.register("manganese_canister", () -> new CompoundItem(new Item.Properties(), MANGANESE_COMPOUND));
    public static final RegistryObject<Item> IRON_CANISTER = ITEMS.register("iron_canister", () -> new CompoundItem(new Item.Properties(), IRON_COMPOUND));
    public static final RegistryObject<Item> COBALT_CANISTER = ITEMS.register("cobalt_canister", () -> new CompoundItem(new Item.Properties(), COBALT_COMPOUND));
    public static final RegistryObject<Item> NICKEL_CANISTER = ITEMS.register("nickel_canister", () -> new CompoundItem(new Item.Properties(), NICKEL_COMPOUND));
    public static final RegistryObject<Item> COPPER_CANISTER = ITEMS.register("copper_canister", () -> new CompoundItem(new Item.Properties(), COPPER_COMPOUND));
    public static final RegistryObject<Item> ZINC_CANISTER = ITEMS.register("zinc_canister", () -> new CompoundItem(new Item.Properties(), ZINC_COMPOUND));
    public static final RegistryObject<Item> GALLIUM_CANISTER = ITEMS.register("gallium_canister", () -> new CompoundItem(new Item.Properties(), GALLIUM_COMPOUND));
    public static final RegistryObject<Item> GERMANIUM_CANISTER = ITEMS.register("germanium_canister", () -> new CompoundItem(new Item.Properties(), GERMANIUM_COMPOUND));
    public static final RegistryObject<Item> ARSENIC_CANISTER = ITEMS.register("arsenic_canister", () -> new CompoundItem(new Item.Properties(), ARSENIC_COMPOUND));
    public static final RegistryObject<Item> SELENIUM_CANISTER = ITEMS.register("selenium_canister", () -> new CompoundItem(new Item.Properties(), SELENIUM_COMPOUND));
     public static final RegistryObject<Item> BROMINE_CANISTER = ITEMS.register("bromine_canister", () -> new CompoundItem(new Item.Properties(), BROMINE_COMPOUND));
    public static final RegistryObject<Item> KRYPTON_CANISTER = ITEMS.register("krypton_canister", () -> new CompoundItem(new Item.Properties(), KRYPTON_COMPOUND));
    public static final RegistryObject<Item> RUBIDIUM_CANISTER = ITEMS.register("rubidium_canister", () -> new CompoundItem(new Item.Properties(), RUBIDIUM_COMPOUND));
    public static final RegistryObject<Item> STRONTIUM_CANISTER = ITEMS.register("strontium_canister", () -> new CompoundItem(new Item.Properties(), STRONTIUM_COMPOUND));
    public static final RegistryObject<Item> YTTRIUM_CANISTER = ITEMS.register("yttrium_canister", () -> new CompoundItem(new Item.Properties(), YTTRIUM_COMPOUND));
    public static final RegistryObject<Item> ZIRCONIUM_CANISTER = ITEMS.register("zirconium_canister", () -> new CompoundItem(new Item.Properties(), ZIRCONIUM_COMPOUND));
    public static final RegistryObject<Item> NIOBIUM_CANISTER = ITEMS.register("niobium_canister", () -> new CompoundItem(new Item.Properties(), NIOBIUM_COMPOUND));
    public static final RegistryObject<Item> MOLYBDENUM_CANISTER = ITEMS.register("molybdenum_canister", () -> new CompoundItem(new Item.Properties(), MOLYBDENUM_COMPOUND));
    public static final RegistryObject<Item> TECHNETIUM_CANISTER = ITEMS.register("technetium_canister", () -> new CompoundItem(new Item.Properties(), TECHNETIUM_COMPOUND));
    public static final RegistryObject<Item> RUTHENIUM_CANISTER = ITEMS.register("ruthenium_canister", () -> new CompoundItem(new Item.Properties(), RUTHENIUM_COMPOUND));
    public static final RegistryObject<Item> RHODIUM_CANISTER = ITEMS.register("rhodium_canister", () -> new CompoundItem(new Item.Properties(), RHODIUM_COMPOUND));
    public static final RegistryObject<Item> PALLADIUM_CANISTER = ITEMS.register("palladium_canister", () -> new CompoundItem(new Item.Properties(), PALLADIUM_COMPOUND));
    public static final RegistryObject<Item> SILVER_CANISTER = ITEMS.register("silver_canister", () -> new CompoundItem(new Item.Properties(), SILVER_COMPOUND));
    public static final RegistryObject<Item> CADMIUM_CANISTER = ITEMS.register("cadmium_canister", () -> new CompoundItem(new Item.Properties(), CADMIUM_COMPOUND));
    public static final RegistryObject<Item> INDIUM_CANISTER = ITEMS.register("indium_canister", () -> new CompoundItem(new Item.Properties(), INDIUM_COMPOUND));
    public static final RegistryObject<Item> TIN_CANISTER = ITEMS.register("tin_canister", () -> new CompoundItem(new Item.Properties(), TIN_COMPOUND));
    public static final RegistryObject<Item> ANTIMONY_CANISTER = ITEMS.register("antimony_canister", () -> new CompoundItem(new Item.Properties(), ANTIMONY_COMPOUND));
    public static final RegistryObject<Item> TELLURIUM_CANISTER = ITEMS.register("tellurium_canister", () -> new CompoundItem(new Item.Properties(), TELLURIUM_COMPOUND));
    public static final RegistryObject<Item> IODINE_CANISTER = ITEMS.register("iodine_canister", () -> new CompoundItem(new Item.Properties(), IODINE_COMPOUND));
    public static final RegistryObject<Item> XENON_CANISTER = ITEMS.register("xenon_canister", () -> new CompoundItem(new Item.Properties(), XENON_COMPOUND));
    public static final RegistryObject<Item> CESIUM_CANISTER = ITEMS.register("cesium_canister", () -> new CompoundItem(new Item.Properties(), CESIUM_COMPOUND));
    public static final RegistryObject<Item> BARIUM_CANISTER = ITEMS.register("barium_canister", () -> new CompoundItem(new Item.Properties(), BARIUM_COMPOUND));
    public static final RegistryObject<Item> LANTHANUM_CANISTER = ITEMS.register("lanthanum_canister", () -> new CompoundItem(new Item.Properties(), LANTHANUM_COMPOUND));
    public static final RegistryObject<Item> CERIUM_CANISTER = ITEMS.register("cerium_canister", () -> new CompoundItem(new Item.Properties(), CERIUM_COMPOUND));
    public static final RegistryObject<Item> PRASEODYMIUM_CANISTER = ITEMS.register("praseodymium_canister", () -> new CompoundItem(new Item.Properties(), PRASEODYMIUM_COMPOUND));
    public static final RegistryObject<Item> NEODYMIUM_CANISTER = ITEMS.register("neodymium_canister", () -> new CompoundItem(new Item.Properties(), NEODYMIUM_COMPOUND));
    public static final RegistryObject<Item> PROMETHIUM_CANISTER = ITEMS.register("promethium_canister", () -> new CompoundItem(new Item.Properties(), PROMETHIUM_COMPOUND));
    public static final RegistryObject<Item> SAMARIUM_CANISTER = ITEMS.register("samarium_canister", () -> new CompoundItem(new Item.Properties(), SAMARIUM_COMPOUND));
    public static final RegistryObject<Item> EUROPIUM_CANISTER = ITEMS.register("europium_canister", () -> new CompoundItem(new Item.Properties(), EUROPIUM_COMPOUND));
    public static final RegistryObject<Item> GADOLINIUM_CANISTER = ITEMS.register("gadolinium_canister", () -> new CompoundItem(new Item.Properties(), GADOLINIUM_COMPOUND));
    public static final RegistryObject<Item> TERBIUM_CANISTER = ITEMS.register("terbium_canister", () -> new CompoundItem(new Item.Properties(), TERBIUM_COMPOUND));
    public static final RegistryObject<Item> DYSPROSIUM_CANISTER = ITEMS.register("dysprosium_canister", () -> new CompoundItem(new Item.Properties(), DYSPROSIUM_COMPOUND));
    public static final RegistryObject<Item> HOLMIUM_CANISTER = ITEMS.register("holmium_canister", () -> new CompoundItem(new Item.Properties(), HOLMIUM_COMPOUND));
    public static final RegistryObject<Item> ERBIUM_CANISTER = ITEMS.register("erbium_canister", () -> new CompoundItem(new Item.Properties(), ERBIUM_COMPOUND));
    public static final RegistryObject<Item> THULIUM_CANISTER = ITEMS.register("thulium_canister", () -> new CompoundItem(new Item.Properties(), THULIUM_COMPOUND));
    public static final RegistryObject<Item> YTTERBIUM_CANISTER = ITEMS.register("ytterbium_canister", () -> new CompoundItem(new Item.Properties(), YTTERBIUM_COMPOUND));
    public static final RegistryObject<Item> LUTETIUM_CANISTER = ITEMS.register("lutetium_canister", () -> new CompoundItem(new Item.Properties(), LUTETIUM_COMPOUND));
    public static final RegistryObject<Item> HAFNIUM_CANISTER = ITEMS.register("hafnium_canister", () -> new CompoundItem(new Item.Properties(), HAFNIUM_COMPOUND));
    public static final RegistryObject<Item> TANTALUM_CANISTER = ITEMS.register("tantalum_canister", () -> new CompoundItem(new Item.Properties(), TANTALUM_COMPOUND));
    public static final RegistryObject<Item> TUNGSTEN_CANISTER = ITEMS.register("tungsten_canister", () -> new CompoundItem(new Item.Properties(), TUNGSTEN_COMPOUND));
    public static final RegistryObject<Item> RHENIUM_CANISTER = ITEMS.register("rhenium_canister", () -> new CompoundItem(new Item.Properties(), RHENIUM_COMPOUND));
    public static final RegistryObject<Item> OSMIUM_CANISTER = ITEMS.register("osmium_canister", () -> new CompoundItem(new Item.Properties(), OSMIUM_COMPOUND));
    public static final RegistryObject<Item> IRIDIUM_CANISTER = ITEMS.register("iridium_canister", () -> new CompoundItem(new Item.Properties(), IRIDIUM_COMPOUND));
    public static final RegistryObject<Item> PLATINUM_CANISTER = ITEMS.register("platinum_canister", () -> new CompoundItem(new Item.Properties(), PLATINUM_COMPOUND));
    public static final RegistryObject<Item> GOLD_CANISTER = ITEMS.register("gold_canister", () -> new CompoundItem(new Item.Properties(), GOLD_COMPOUND));
     public static final RegistryObject<Item> MERCURY_CANISTER = ITEMS.register("mercury_canister", () -> new CompoundItem(new Item.Properties(), MERCURY_COMPOUND));
    public static final RegistryObject<Item> THALLIUM_CANISTER = ITEMS.register("thallium_canister", () -> new CompoundItem(new Item.Properties(), THALLIUM_COMPOUND));
    public static final RegistryObject<Item> LEAD_CANISTER = ITEMS.register("lead_canister", () -> new CompoundItem(new Item.Properties(), LEAD_COMPOUND));
    public static final RegistryObject<Item> BISMUTH_CANISTER = ITEMS.register("bismuth_canister", () -> new CompoundItem(new Item.Properties(), BISMUTH_COMPOUND));
    public static final RegistryObject<Item> POLONIUM_CANISTER = ITEMS.register("polonium_canister", () -> new CompoundItem(new Item.Properties(), POLONIUM_COMPOUND));
    public static final RegistryObject<Item> ASTATINE_CANISTER = ITEMS.register("astatine_canister", () -> new CompoundItem(new Item.Properties(), ASTATINE_COMPOUND));
    public static final RegistryObject<Item> RADON_CANISTER = ITEMS.register("radon_canister", () -> new CompoundItem(new Item.Properties(), RADON_COMPOUND));
    public static final RegistryObject<Item> FRANCIUM_CANISTER = ITEMS.register("francium_canister", () -> new CompoundItem(new Item.Properties(), FRANCIUM_COMPOUND));
    public static final RegistryObject<Item> RADIUM_CANISTER = ITEMS.register("radium_canister", () -> new CompoundItem(new Item.Properties(), RADIUM_COMPOUND));
    public static final RegistryObject<Item> ACTINIUM_CANISTER = ITEMS.register("actinium_canister", () -> new CompoundItem(new Item.Properties(), ACTINIUM_COMPOUND));
    public static final RegistryObject<Item> THORIUM_CANISTER = ITEMS.register("thorium_canister", () -> new CompoundItem(new Item.Properties(), THORIUM_COMPOUND));
    public static final RegistryObject<Item> PROTACTINIUM_CANISTER = ITEMS.register("protactinium_canister", () -> new CompoundItem(new Item.Properties(), PROTACTINIUM_COMPOUND));
    public static final RegistryObject<Item> URANIUM_CANISTER = ITEMS.register("uranium_canister", () -> new CompoundItem(new Item.Properties(), URANIUM_COMPOUND));

    // Gas
    public static final RegistryObject<Item> COMPRESSED_HYDROGEN = ITEMS.register("compressed_hydrogen", () -> new CompoundItem(new Item.Properties(), HYDROGEN_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_HELIUM = ITEMS.register("compressed_helium", () -> new CompoundItem(new Item.Properties(), HELIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_LITHIUM = ITEMS.register("compressed_lithium", () -> new CompoundItem(new Item.Properties(), LITHIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_BERYLLIUM = ITEMS.register("compressed_beryllium", () -> new CompoundItem(new Item.Properties(), BERYLLIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_BORON = ITEMS.register("compressed_boron", () -> new CompoundItem(new Item.Properties(), BORON_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_CARBON = ITEMS.register("compressed_carbon", () -> new CompoundItem(new Item.Properties(), CARBON_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_NITROGEN = ITEMS.register("compressed_nitrogen", () -> new CompoundItem(new Item.Properties(), NITROGEN_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_OXYGEN = ITEMS.register("compressed_oxygen", () -> new CompoundItem(new Item.Properties(), OXYGEN_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_FLUORINE = ITEMS.register("compressed_fluorine", () -> new CompoundItem(new Item.Properties(), FLUORINE_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_NEON = ITEMS.register("compressed_neon", () -> new CompoundItem(new Item.Properties(), NEON_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_SODIUM = ITEMS.register("compressed_sodium", () -> new CompoundItem(new Item.Properties(), SODIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_MAGNESIUM = ITEMS.register("compressed_magnesium", () -> new CompoundItem(new Item.Properties(), MAGNESIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_ALUMINIUM = ITEMS.register("compressed_aluminium", () -> new CompoundItem(new Item.Properties(), ALUMINIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_SILICON = ITEMS.register("compressed_silicon", () -> new CompoundItem(new Item.Properties(), SILICON_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_PHOSPHORUS = ITEMS.register("compressed_phosphorus", () -> new CompoundItem(new Item.Properties(), PHOSPHORUS_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_SULFUR = ITEMS.register("compressed_sulfur", () -> new CompoundItem(new Item.Properties(), SULFUR_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_CHLORINE = ITEMS.register("compressed_chlorine", () -> new CompoundItem(new Item.Properties(), CHLORINE_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_ARGON = ITEMS.register("compressed_argon", () -> new CompoundItem(new Item.Properties(), ARGON_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_POTASSIUM = ITEMS.register("compressed_potassium", () -> new CompoundItem(new Item.Properties(), POTASSIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_CALCIUM = ITEMS.register("compressed_calcium", () -> new CompoundItem(new Item.Properties(), CALCIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_SCANDIUM = ITEMS.register("compressed_scandium", () -> new CompoundItem(new Item.Properties(), SCANDIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_TITANIUM = ITEMS.register("compressed_titanium", () -> new CompoundItem(new Item.Properties(), TITANIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_VANADIUM = ITEMS.register("compressed_vanadium", () -> new CompoundItem(new Item.Properties(), VANADIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_CHROMIUM = ITEMS.register("compressed_chromium", () -> new CompoundItem(new Item.Properties(), CHROMIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_MANGANESE = ITEMS.register("compressed_manganese", () -> new CompoundItem(new Item.Properties(), MANGANESE_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_IRON = ITEMS.register("compressed_iron", () -> new CompoundItem(new Item.Properties(), IRON_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_COBALT = ITEMS.register("compressed_cobalt", () -> new CompoundItem(new Item.Properties(), COBALT_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_NICKEL = ITEMS.register("compressed_nickel", () -> new CompoundItem(new Item.Properties(), NICKEL_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_COPPER = ITEMS.register("compressed_copper", () -> new CompoundItem(new Item.Properties(), COPPER_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_ZINC = ITEMS.register("compressed_zinc", () -> new CompoundItem(new Item.Properties(), ZINC_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_GALLIUM = ITEMS.register("compressed_gallium", () -> new CompoundItem(new Item.Properties(), GALLIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_GERMANIUM = ITEMS.register("compressed_germanium", () -> new CompoundItem(new Item.Properties(), GERMANIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_ARSENIC = ITEMS.register("compressed_arsenic", () -> new CompoundItem(new Item.Properties(), ARSENIC_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_SELENIUM = ITEMS.register("compressed_selenium", () -> new CompoundItem(new Item.Properties(), SELENIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_BROMINE = ITEMS.register("compressed_bromine", () -> new CompoundItem(new Item.Properties(), BROMINE_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_KRYPTON = ITEMS.register("compressed_krypton", () -> new CompoundItem(new Item.Properties(), KRYPTON_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_RUBIDIUM = ITEMS.register("compressed_rubidium", () -> new CompoundItem(new Item.Properties(), RUBIDIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_STRONTIUM = ITEMS.register("compressed_strontium", () -> new CompoundItem(new Item.Properties(), STRONTIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_YTTRIUM = ITEMS.register("compressed_yttrium", () -> new CompoundItem(new Item.Properties(), YTTRIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_ZIRCONIUM = ITEMS.register("compressed_zirconium", () -> new CompoundItem(new Item.Properties(), ZIRCONIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_NIOBIUM = ITEMS.register("compressed_niobium", () -> new CompoundItem(new Item.Properties(), NIOBIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_MOLYBDENUM = ITEMS.register("compressed_molybdenum", () -> new CompoundItem(new Item.Properties(), MOLYBDENUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_TECHNETIUM = ITEMS.register("compressed_technetium", () -> new CompoundItem(new Item.Properties(), TECHNETIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_RUTHENIUM = ITEMS.register("compressed_ruthenium", () -> new CompoundItem(new Item.Properties(), RUTHENIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_RHODIUM = ITEMS.register("compressed_rhodium", () -> new CompoundItem(new Item.Properties(), RHODIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_PALLADIUM = ITEMS.register("compressed_palladium", () -> new CompoundItem(new Item.Properties(), PALLADIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_SILVER = ITEMS.register("compressed_silver", () -> new CompoundItem(new Item.Properties(), SILVER_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_CADMIUM = ITEMS.register("compressed_cadmium", () -> new CompoundItem(new Item.Properties(), CADMIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_INDIUM = ITEMS.register("compressed_indium", () -> new CompoundItem(new Item.Properties(), INDIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_TIN = ITEMS.register("compressed_tin", () -> new CompoundItem(new Item.Properties(), TIN_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_ANTIMONY = ITEMS.register("compressed_antimony", () -> new CompoundItem(new Item.Properties(), ANTIMONY_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_TELLURIUM = ITEMS.register("compressed_tellurium", () -> new CompoundItem(new Item.Properties(), TELLURIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_IODINE = ITEMS.register("compressed_iodine", () -> new CompoundItem(new Item.Properties(), IODINE_COMPOUND));
     public static final RegistryObject<Item> COMPRESSED_XENON = ITEMS.register("compressed_xenon", () -> new CompoundItem(new Item.Properties(), XENON_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_CESIUM = ITEMS.register("compressed_cesium", () -> new CompoundItem(new Item.Properties(), CESIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_BARIUM = ITEMS.register("compressed_barium", () -> new CompoundItem(new Item.Properties(), BARIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_LANTHANUM = ITEMS.register("compressed_lanthanum", () -> new CompoundItem(new Item.Properties(), LANTHANUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_CERIUM = ITEMS.register("compressed_cerium", () -> new CompoundItem(new Item.Properties(), CERIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_PRASEODYMIUM = ITEMS.register("compressed_praseodymium", () -> new CompoundItem(new Item.Properties(), PRASEODYMIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_NEODYMIUM = ITEMS.register("compressed_neodymium", () -> new CompoundItem(new Item.Properties(), NEODYMIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_PROMETHIUM = ITEMS.register("compressed_promethium", () -> new CompoundItem(new Item.Properties(), PROMETHIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_SAMARIUM = ITEMS.register("compressed_samarium", () -> new CompoundItem(new Item.Properties(), SAMARIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_EUROPIUM = ITEMS.register("compressed_europium", () -> new CompoundItem(new Item.Properties(), EUROPIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_GADOLINIUM = ITEMS.register("compressed_gadolinium", () -> new CompoundItem(new Item.Properties(), GADOLINIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_TERBIUM = ITEMS.register("compressed_terbium", () -> new CompoundItem(new Item.Properties(), TERBIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_DYSPROSIUM = ITEMS.register("compressed_dysprosium", () -> new CompoundItem(new Item.Properties(), DYSPROSIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_HOLMIUM = ITEMS.register("compressed_holmium", () -> new CompoundItem(new Item.Properties(), HOLMIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_ERBIUM = ITEMS.register("compressed_erbium", () -> new CompoundItem(new Item.Properties(), ERBIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_THULIUM = ITEMS.register("compressed_thulium", () -> new CompoundItem(new Item.Properties(), THULIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_YTTERBIUM = ITEMS.register("compressed_ytterbium", () -> new CompoundItem(new Item.Properties(), YTTERBIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_LUTETIUM = ITEMS.register("compressed_lutetium", () -> new CompoundItem(new Item.Properties(), LUTETIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_HAFNIUM = ITEMS.register("compressed_hafnium", () -> new CompoundItem(new Item.Properties(), HAFNIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_TANTALUM = ITEMS.register("compressed_tantalum", () -> new CompoundItem(new Item.Properties(), TANTALUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_TUNGSTEN = ITEMS.register("compressed_tungsten", () -> new CompoundItem(new Item.Properties(), TUNGSTEN_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_RHENIUM = ITEMS.register("compressed_rhenium", () -> new CompoundItem(new Item.Properties(), RHENIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_OSMIUM = ITEMS.register("compressed_osmium", () -> new CompoundItem(new Item.Properties(), OSMIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_IRIDIUM = ITEMS.register("compressed_iridium", () -> new CompoundItem(new Item.Properties(), IRIDIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_PLATINUM = ITEMS.register("compressed_platinum", () -> new CompoundItem(new Item.Properties(), PLATINUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_GOLD = ITEMS.register("compressed_gold", () -> new CompoundItem(new Item.Properties(), GOLD_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_MERCURY = ITEMS.register("compressed_mercury", () -> new CompoundItem(new Item.Properties(), MERCURY_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_THALLIUM = ITEMS.register("compressed_thallium", () -> new CompoundItem(new Item.Properties(), THALLIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_LEAD = ITEMS.register("compressed_lead", () -> new CompoundItem(new Item.Properties(), LEAD_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_BISMUTH = ITEMS.register("compressed_bismuth", () -> new CompoundItem(new Item.Properties(), BISMUTH_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_POLONIUM = ITEMS.register("compressed_polonium", () -> new CompoundItem(new Item.Properties(), POLONIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_ASTATINE = ITEMS.register("compressed_astatine", () -> new CompoundItem(new Item.Properties(), ASTATINE_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_RADON = ITEMS.register("compressed_radon", () -> new CompoundItem(new Item.Properties(), RADON_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_FRANCIUM = ITEMS.register("compressed_francium", () -> new CompoundItem(new Item.Properties(), FRANCIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_RADIUM = ITEMS.register("compressed_radium", () -> new CompoundItem(new Item.Properties(), RADIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_ACTINIUM = ITEMS.register("compressed_actinium", () -> new CompoundItem(new Item.Properties(), ACTINIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_THORIUM = ITEMS.register("compressed_thorium", () -> new CompoundItem(new Item.Properties(), THORIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_PROTACTINIUM = ITEMS.register("compressed_protactinium", () -> new CompoundItem(new Item.Properties(), PROTACTINIUM_COMPOUND));
    public static final RegistryObject<Item> COMPRESSED_URANIUM = ITEMS.register("compressed_uranium", () -> new CompoundItem(new Item.Properties(), URANIUM_COMPOUND));

    public static final RegistryObject<Block> ALLOY_FURNACE = BLOCKS.register("alloy_furnace", () -> new AlloyFurnaceBlock(BlockBehaviour.Properties.of(Material.METAL).lightLevel(b -> b.getValue(BlockStateProperties.LIT)?15:0))); // TODO: Set this to the correct material later.
    public static final RegistryObject<BlockEntityType<AlloyFurnaceBlockEntity>> ALLOY_FURNACE_BE = BLOCK_ENTITIES.register("alloy_furnace", () -> BlockEntityType.Builder.of(AlloyFurnaceBlockEntity::new, ALLOY_FURNACE.get()).build(null));
    public static final RegistryObject<Item> ALLOY_FURNACE_ITEM = ITEMS.register("alloy_furnace", () -> new BlockItem(ALLOY_FURNACE.get(), new Item.Properties()));

    public static final RegistryObject<MenuType<AlloyFurnaceMenu>> ALLOY_FURNACE_MENU = MENU_TYPES.register("alloy_furnace_menu", () -> IForgeMenuType.create(AlloyFurnaceMenu::new));

    public static final RegistryObject<RecipeSerializer<AlloySmeltingRecipe>> ALLOY_SMELTING_SERIALIZER = RECIPE_SERIALIZERS.register("alloy_smelting", () -> AlloySmeltingRecipe.Serializer.INSTANCE);

    public BMBC_Main(IEventBus modEventBus) {
        BLOCKS.register(modEventBus);
        BLOCK_ENTITIES.register(modEventBus);
        ITEMS.register(modEventBus);
        MENU_TYPES.register(modEventBus);
        RECIPE_SERIALIZERS.register(modEventBus);
    }

    public static List<RegistryObject<Item>> doDatagen() {
        return new ArrayList<>() {{
            // Solid
            add(HYDROGEN_INGOT);
            add(HELIUM_INGOT);
            add(LITHIUM_INGOT);
            add(BERYLLIUM_INGOT);
            add(BORON_INGOT);
            add(CARBON_INGOT);
            add(NITROGEN_INGOT);
            add(OXYGEN_INGOT);
            add(FLUORINE_INGOT);
            add(NEON_INGOT);
            add(SODIUM_INGOT);
            add(MAGNESIUM_INGOT);
            add(ALUMINIUM_INGOT);
            add(SILICON_CRYSTAL);
            add(WHITE_PHOSPHORUS);
            add(RED_PHOSPHORUS);
            add(BLACK_PHOSPHORUS);
            add(SULFUR_CRYSTAL);
            add(CHLORINE_INGOT);
            add(ARGON_INGOT);
            add(POTASSIUM_INGOT);
            add(CALCIUM_ROCK);
            add(SCANDIUM_INGOT);
            add(TITANIUM_INGOT);
            add(VANADIUM_INGOT);
            add(CHROMIUM_CRYSTAL);
            add(MANGANESE_INGOT);
            //add(IRON_INGOT);
            add(COBALT_INGOT);
            add(NICKEL_INGOT);
            //add(COPPER_INGOT);
            add(ZINC_INGOT);
            add(GALLIUM_INGOT);
            add(GERMANIUM_INGOT);
            add(ARSENIC_INGOT);
            add(SELENIUM_INGOT);
            add(BROMINE_INGOT);
            add(KRYPTON_INGOT);
            add(RUBIDIUM_INGOT);
            add(STRONTIUM_INGOT);
            add(YTTRIUM_INGOT);
            add(ZIRCONIUM_INGOT);
            add(NIOBIUM_INGOT);
            add(MOLYBDENUM_INGOT);
            add(TECHNETIUM_INGOT);
            add(RUTHENIUM_INGOT);
            add(RHODIUM_INGOT);
            add(PALLADIUM_INGOT);
            add(SILVER_INGOT);
            add(CADMIUM_INGOT);
            add(INDIUM_INGOT);
            add(TIN_INGOT);
            add(ANTIMONY_INGOT);
            add(TELLURIUM_INGOT);
            add(IODINE_INGOT);
            add(XENON_INGOT);
            add(CESIUM_INGOT);
            add(BARIUM_INGOT);
            add(LANTHANUM_INGOT);
            add(CERIUM_INGOT);
            add(PRASEODYMIUM_INGOT);
            add(NEODYMIUM_INGOT);
            add(PROMETHIUM_INGOT);
            add(SAMARIUM_INGOT);
            add(EUROPIUM_INGOT);
            add(GADOLINIUM_INGOT);
            add(TERBIUM_INGOT);
            add(DYSPROSIUM_INGOT);
            add(HOLMIUM_INGOT);
            add(ERBIUM_INGOT);
            add(THULIUM_INGOT);
            add(YTTERBIUM_INGOT);
            add(LUTETIUM_INGOT);
            add(HAFNIUM_INGOT);
            add(TANTALUM_INGOT);
            add(TUNGSTEN_INGOT);
            add(RHENIUM_INGOT);
            add(OSMIUM_INGOT);
            add(IRIDIUM_INGOT);
            add(PLATINUM_INGOT);
            //add(GOLD_INGOT);
            add(MERCURY_INGOT);
            add(THALLIUM_INGOT);
            add(LEAD_INGOT);
            add(BISMUTH_INGOT);
            add(POLONIUM_INGOT);
            add(ASTATINE_INGOT);
            add(RADON_INGOT);
            add(FRANCIUM_INGOT);
            add(RADIUM_INGOT);
            add(ACTINIUM_INGOT);
            add(THORIUM_INGOT);
            add(PROTACTINIUM_INGOT);
            add(URANIUM_INGOT);

            // Liquid
            add(HYDROGEN_CANISTER);
            add(HELIUM_CANISTER);
            add(LITHIUM_CANISTER);
            add(BERYLLIUM_CANISTER);
            add(BORON_CANISTER);
            add(CARBON_CANISTER);
            add(NITROGEN_CANISTER);
            add(OXYGEN_CANISTER);
            add(FLUORINE_CANISTER);
            add(NEON_CANISTER);
            add(SODIUM_CANISTER);
            add(MAGNESIUM_CANISTER);
            add(ALUMINIUM_CANISTER);
            add(SILICON_CANISTER);
            add(PHOSPHORUS_CANISTER);
            add(SULFUR_CANISTER);
            add(CHLORINE_CANISTER);
            add(ARGON_CANISTER);
            add(POTASSIUM_CANISTER);
            add(CALCIUM_CANISTER);
            add(SCANDIUM_CANISTER);
            add(TITANIUM_CANISTER);
            add(VANADIUM_CANISTER);
            add(CHROMIUM_CANISTER);
            add(MANGANESE_CANISTER);
            add(IRON_CANISTER);
            add(COBALT_CANISTER);
            add(NICKEL_CANISTER);
            add(COPPER_CANISTER);
            add(ZINC_CANISTER);
            add(GALLIUM_CANISTER);
            add(GERMANIUM_CANISTER);
            add(ARSENIC_CANISTER);
            add(SELENIUM_CANISTER);
            add(BROMINE_CANISTER);
            add(KRYPTON_CANISTER);
            add(RUBIDIUM_CANISTER);
            add(STRONTIUM_CANISTER);
            add(YTTRIUM_CANISTER);
            add(ZIRCONIUM_CANISTER);
            add(NIOBIUM_CANISTER);
            add(MOLYBDENUM_CANISTER);
            add(TECHNETIUM_CANISTER);
            add(RUTHENIUM_CANISTER);
            add(RHODIUM_CANISTER);
            add(PALLADIUM_CANISTER);
            add(SILVER_CANISTER);
            add(CADMIUM_CANISTER);
            add(INDIUM_CANISTER);
            add(TIN_CANISTER);
            add(ANTIMONY_CANISTER);
            add(TELLURIUM_CANISTER);
            add(IODINE_CANISTER);
            add(XENON_CANISTER);
            add(CESIUM_CANISTER);
            add(BARIUM_CANISTER);
            add(LANTHANUM_CANISTER);
            add(CERIUM_CANISTER);
            add(PRASEODYMIUM_CANISTER);
            add(NEODYMIUM_CANISTER);
            add(PROMETHIUM_CANISTER);
            add(SAMARIUM_CANISTER);
            add(EUROPIUM_CANISTER);
            add(GADOLINIUM_CANISTER);
            add(TERBIUM_CANISTER);
            add(DYSPROSIUM_CANISTER);
            add(HOLMIUM_CANISTER);
            add(ERBIUM_CANISTER);
            add(THULIUM_CANISTER);
            add(YTTERBIUM_CANISTER);
            add(LUTETIUM_CANISTER);
            add(HAFNIUM_CANISTER);
            add(TANTALUM_CANISTER);
            add(TUNGSTEN_CANISTER);
            add(RHENIUM_CANISTER);
            add(OSMIUM_CANISTER);
            add(IRIDIUM_CANISTER);
            add(PLATINUM_CANISTER);
            add(GOLD_CANISTER);
            add(MERCURY_CANISTER);
            add(THALLIUM_CANISTER);
            add(LEAD_CANISTER);
            add(BISMUTH_CANISTER);
            add(POLONIUM_CANISTER);
            add(ASTATINE_CANISTER);
            add(RADON_CANISTER);
            add(FRANCIUM_CANISTER);
            add(RADIUM_CANISTER);
            add(ACTINIUM_CANISTER);
            add(THORIUM_CANISTER);
            add(PROTACTINIUM_CANISTER);
            add(URANIUM_CANISTER);

            // Gas
            add(COMPRESSED_HYDROGEN);
            add(COMPRESSED_HELIUM);
            add(COMPRESSED_LITHIUM);
            add(COMPRESSED_BERYLLIUM);
            add(COMPRESSED_BORON);
            add(COMPRESSED_CARBON);
            add(COMPRESSED_NITROGEN);
            add(COMPRESSED_OXYGEN);
            add(COMPRESSED_FLUORINE);
            add(COMPRESSED_NEON);
            add(COMPRESSED_SODIUM);
            add(COMPRESSED_MAGNESIUM);
            add(COMPRESSED_ALUMINIUM);
            add(COMPRESSED_SILICON);
            add(COMPRESSED_PHOSPHORUS);
            add(COMPRESSED_SULFUR);
            add(COMPRESSED_CHLORINE);
            add(COMPRESSED_ARGON);
            add(COMPRESSED_POTASSIUM);
            add(COMPRESSED_CALCIUM);
            add(COMPRESSED_SCANDIUM);
            add(COMPRESSED_TITANIUM);
            add(COMPRESSED_VANADIUM);
            add(COMPRESSED_CHROMIUM);
            add(COMPRESSED_MANGANESE);
            add(COMPRESSED_IRON);
            add(COMPRESSED_COBALT);
            add(COMPRESSED_NICKEL);
            add(COMPRESSED_COPPER);
            add(COMPRESSED_ZINC);
            add(COMPRESSED_GALLIUM);
            add(COMPRESSED_GERMANIUM);
            add(COMPRESSED_ARSENIC);
            add(COMPRESSED_SELENIUM);
            add(COMPRESSED_BROMINE);
            add(COMPRESSED_KRYPTON);
            add(COMPRESSED_RUBIDIUM);
            add(COMPRESSED_STRONTIUM);
            add(COMPRESSED_YTTRIUM);
            add(COMPRESSED_ZIRCONIUM);
            add(COMPRESSED_NIOBIUM);
            add(COMPRESSED_MOLYBDENUM);
            add(COMPRESSED_TECHNETIUM);
            add(COMPRESSED_RUTHENIUM);
            add(COMPRESSED_RHODIUM);
            add(COMPRESSED_PALLADIUM);
            add(COMPRESSED_SILVER);
            add(COMPRESSED_CADMIUM);
            add(COMPRESSED_INDIUM);
            add(COMPRESSED_TIN);
            add(COMPRESSED_ANTIMONY);
            add(COMPRESSED_TELLURIUM);
            add(COMPRESSED_IODINE);
            add(COMPRESSED_XENON);
            add(COMPRESSED_CESIUM);
            add(COMPRESSED_BARIUM);
            add(COMPRESSED_LANTHANUM);
            add(COMPRESSED_CERIUM);
            add(COMPRESSED_PRASEODYMIUM);
            add(COMPRESSED_NEODYMIUM);
            add(COMPRESSED_PROMETHIUM);
            add(COMPRESSED_SAMARIUM);
            add(COMPRESSED_EUROPIUM);
            add(COMPRESSED_GADOLINIUM);
            add(COMPRESSED_TERBIUM);
            add(COMPRESSED_DYSPROSIUM);
            add(COMPRESSED_HOLMIUM);
            add(COMPRESSED_ERBIUM);
            add(COMPRESSED_THULIUM);
            add(COMPRESSED_YTTERBIUM);
            add(COMPRESSED_LUTETIUM);
            add(COMPRESSED_HAFNIUM);
            add(COMPRESSED_TANTALUM);
            add(COMPRESSED_TUNGSTEN);
            add(COMPRESSED_RHENIUM);
            add(COMPRESSED_OSMIUM);
            add(COMPRESSED_IRIDIUM);
            add(COMPRESSED_PLATINUM);
            add(COMPRESSED_GOLD);
            add(COMPRESSED_MERCURY);
            add(COMPRESSED_THALLIUM);
            add(COMPRESSED_LEAD);
            add(COMPRESSED_BISMUTH);
            add(COMPRESSED_POLONIUM);
            add(COMPRESSED_ASTATINE);
            add(COMPRESSED_RADON);
            add(COMPRESSED_FRANCIUM);
            add(COMPRESSED_RADIUM);
            add(COMPRESSED_ACTINIUM);
            add(COMPRESSED_THORIUM);
            add(COMPRESSED_PROTACTINIUM);
            add(COMPRESSED_URANIUM);
        }};
    }

    @Mod.EventBusSubscriber(modid = MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
    public static class ClientEvents {
        @SubscribeEvent
        public static void doSetup(FMLClientSetupEvent event) {
            MenuScreens.register(ALLOY_FURNACE_MENU.get(), AlloyFurnaceScreen::new);
        }

        @SubscribeEvent
        public static void registerBlockRender(EntityRenderersEvent.RegisterRenderers event) {
            event.registerBlockEntityRenderer(ALLOY_FURNACE_BE.get(), AlloyFurnaceBlockEntityRenderer::new);
        }
    }

    @Mod.EventBusSubscriber(modid = MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
    public static class ModEvents {
        @SubscribeEvent
        public static void doCompatStuff(FMLLoadCompleteEvent event) {
            List<CompoundItem> compoundItems = new ArrayList<>();
            for (Item item:ForgeRegistries.ITEMS.getValues()) {
                if (item instanceof CompoundItem compoundItem) compoundItems.add(compoundItem);
            }
            for (Item item:ForgeRegistries.ITEMS.getValues()) {
                if (item instanceof CompoundItem) continue;
                boolean ImTheException = false;
                if (ForgeRegistries.ITEMS.getKey(item).getPath() == "iron_ingot") {
                    CompoundItem.addCompatibleItem(item, new Compound(IRON));
                    ImTheException = true;
                } else if (ForgeRegistries.ITEMS.getKey(item).getPath() == "copper_ingot") {
                    CompoundItem.addCompatibleItem(item, new Compound(COPPER));
                    ImTheException = true;
                } else if (ForgeRegistries.ITEMS.getKey(item).getPath() == "gold_ingot") {
                    CompoundItem.addCompatibleItem(item, new Compound(GOLD));
                    ImTheException = true;
                }
                if (ImTheException) continue;
                for (CompoundItem compoundItem:compoundItems) {
                    if (ForgeRegistries.ITEMS.getKey(item).getPath().replace("aluminum","aluminium") == ForgeRegistries.ITEMS.getKey(compoundItem).getPath()) {
                        CompoundItem.addCompatibleItem(item, compoundItem.getCompound());
                        break;
                    }
                }
            }
        }

        @SubscribeEvent
        public static void addCreative(CreativeModeTabEvent.BuildContents event) {
            if (event.getTab() == ModMachinesCreativeModeTab.BMBC_MACHINES) {
                event.accept(ALLOY_FURNACE_ITEM);
            }
            if (event.getTab() == ModResourcesCreativeModeTab.BMBC_RESOURCES) {
                // Solid
                event.accept(HYDROGEN_INGOT);
                event.accept(HELIUM_INGOT);
                event.accept(LITHIUM_INGOT);
                event.accept(BERYLLIUM_INGOT);
                event.accept(BORON_INGOT);
                event.accept(CARBON_INGOT);
                event.accept(NITROGEN_INGOT);
                event.accept(OXYGEN_INGOT);
                event.accept(FLUORINE_INGOT);
                event.accept(NEON_INGOT);
                event.accept(SODIUM_INGOT);
                event.accept(MAGNESIUM_INGOT);
                event.accept(ALUMINIUM_INGOT);
                event.accept(SILICON_CRYSTAL);
                event.accept(WHITE_PHOSPHORUS);
                event.accept(RED_PHOSPHORUS);
                event.accept(BLACK_PHOSPHORUS);
                event.accept(SULFUR_CRYSTAL);
                event.accept(CHLORINE_INGOT);
                event.accept(ARGON_INGOT);
                event.accept(POTASSIUM_INGOT);
                event.accept(CALCIUM_ROCK);
                event.accept(SCANDIUM_INGOT);
                event.accept(TITANIUM_INGOT);
                event.accept(VANADIUM_INGOT);
                event.accept(CHROMIUM_CRYSTAL);
                event.accept(MANGANESE_INGOT);
                //event.accept(IRON_INGOT);
                event.accept(COBALT_INGOT);
                event.accept(NICKEL_INGOT);
                //event.accept(COPPER_INGOT);
                event.accept(ZINC_INGOT);
                event.accept(GALLIUM_INGOT);
                event.accept(GERMANIUM_INGOT);
                event.accept(ARSENIC_INGOT);
                event.accept(SELENIUM_INGOT);
                event.accept(BROMINE_INGOT);
                event.accept(KRYPTON_INGOT);
                event.accept(RUBIDIUM_INGOT);
                event.accept(STRONTIUM_INGOT);
                event.accept(YTTRIUM_INGOT);
                event.accept(ZIRCONIUM_INGOT);
                event.accept(NIOBIUM_INGOT);
                event.accept(MOLYBDENUM_INGOT);
                event.accept(TECHNETIUM_INGOT);
                event.accept(RUTHENIUM_INGOT);
                event.accept(RHODIUM_INGOT);
                event.accept(PALLADIUM_INGOT);
                event.accept(SILVER_INGOT);
                event.accept(CADMIUM_INGOT);
                event.accept(INDIUM_INGOT);
                event.accept(TIN_INGOT);
                event.accept(ANTIMONY_INGOT);
                event.accept(TELLURIUM_INGOT);
                event.accept(IODINE_INGOT);
                event.accept(XENON_INGOT);
                event.accept(CESIUM_INGOT);
                event.accept(BARIUM_INGOT);
                event.accept(LANTHANUM_INGOT);
                event.accept(CERIUM_INGOT);
                event.accept(PRASEODYMIUM_INGOT);
                event.accept(NEODYMIUM_INGOT);
                event.accept(PROMETHIUM_INGOT);
                event.accept(SAMARIUM_INGOT);
                event.accept(EUROPIUM_INGOT);
                event.accept(GADOLINIUM_INGOT);
                event.accept(TERBIUM_INGOT);
                event.accept(DYSPROSIUM_INGOT);
                event.accept(HOLMIUM_INGOT);
                event.accept(ERBIUM_INGOT);
                event.accept(THULIUM_INGOT);
                event.accept(YTTERBIUM_INGOT);
                event.accept(LUTETIUM_INGOT);
                event.accept(HAFNIUM_INGOT);
                event.accept(TANTALUM_INGOT);
                event.accept(TUNGSTEN_INGOT);
                event.accept(RHENIUM_INGOT);
                event.accept(OSMIUM_INGOT);
                event.accept(IRIDIUM_INGOT);
                event.accept(PLATINUM_INGOT);
                //event.accept(GOLD_INGOT);
                event.accept(MERCURY_INGOT);
                event.accept(THALLIUM_INGOT);
                event.accept(LEAD_INGOT);
                event.accept(BISMUTH_INGOT);
                event.accept(POLONIUM_INGOT);
                event.accept(ASTATINE_INGOT);
                event.accept(RADON_INGOT);
                event.accept(FRANCIUM_INGOT);
                event.accept(RADIUM_INGOT);
                event.accept(ACTINIUM_INGOT);
                event.accept(THORIUM_INGOT);
                event.accept(PROTACTINIUM_INGOT);
                event.accept(URANIUM_INGOT);
            }
            if (event.getTab() == ModFluidsCreativeModeTab.BMBC_FLUIDS) {
                // Liquid
                event.accept(HYDROGEN_CANISTER);
                event.accept(HELIUM_CANISTER);
                event.accept(LITHIUM_CANISTER);
                event.accept(BERYLLIUM_CANISTER);
                event.accept(BORON_CANISTER);
                event.accept(CARBON_CANISTER);
                event.accept(NITROGEN_CANISTER);
                event.accept(OXYGEN_CANISTER);
                event.accept(FLUORINE_CANISTER);
                event.accept(NEON_CANISTER);
                event.accept(SODIUM_CANISTER);
                event.accept(MAGNESIUM_CANISTER);
                event.accept(ALUMINIUM_CANISTER);
                event.accept(SILICON_CANISTER);
                event.accept(PHOSPHORUS_CANISTER);
                event.accept(SULFUR_CANISTER);
                event.accept(CHLORINE_CANISTER);
                event.accept(ARGON_CANISTER);
                event.accept(POTASSIUM_CANISTER);
                event.accept(CALCIUM_CANISTER);
                event.accept(SCANDIUM_CANISTER);
                event.accept(TITANIUM_CANISTER);
                event.accept(VANADIUM_CANISTER);
                event.accept(CHROMIUM_CANISTER);
                event.accept(MANGANESE_CANISTER);
                event.accept(IRON_CANISTER);
                event.accept(COBALT_CANISTER);
                event.accept(NICKEL_CANISTER);
                event.accept(COPPER_CANISTER);
                event.accept(ZINC_CANISTER);
                event.accept(GALLIUM_CANISTER);
                event.accept(GERMANIUM_CANISTER);
                event.accept(ARSENIC_CANISTER);
                event.accept(SELENIUM_CANISTER);
                event.accept(BROMINE_CANISTER);
                event.accept(KRYPTON_CANISTER);
                event.accept(RUBIDIUM_CANISTER);
                event.accept(STRONTIUM_CANISTER);
                event.accept(YTTRIUM_CANISTER);
                event.accept(ZIRCONIUM_CANISTER);
                event.accept(NIOBIUM_CANISTER);
                event.accept(MOLYBDENUM_CANISTER);
                event.accept(TECHNETIUM_CANISTER);
                event.accept(RUTHENIUM_CANISTER);
                event.accept(RHODIUM_CANISTER);
                event.accept(PALLADIUM_CANISTER);
                event.accept(SILVER_CANISTER);
                event.accept(CADMIUM_CANISTER);
                event.accept(INDIUM_CANISTER);
                event.accept(TIN_CANISTER);
                event.accept(ANTIMONY_CANISTER);
                event.accept(TELLURIUM_CANISTER);
                event.accept(IODINE_CANISTER);
                event.accept(XENON_CANISTER);
                event.accept(CESIUM_CANISTER);
                event.accept(BARIUM_CANISTER);
                event.accept(LANTHANUM_CANISTER);
                event.accept(CERIUM_CANISTER);
                event.accept(PRASEODYMIUM_CANISTER);
                event.accept(NEODYMIUM_CANISTER);
                event.accept(PROMETHIUM_CANISTER);
                event.accept(SAMARIUM_CANISTER);
                event.accept(EUROPIUM_CANISTER);
                event.accept(GADOLINIUM_CANISTER);
                event.accept(TERBIUM_CANISTER);
                event.accept(DYSPROSIUM_CANISTER);
                event.accept(HOLMIUM_CANISTER);
                event.accept(ERBIUM_CANISTER);
                event.accept(THULIUM_CANISTER);
                event.accept(YTTERBIUM_CANISTER);
                event.accept(LUTETIUM_CANISTER);
                event.accept(HAFNIUM_CANISTER);
                event.accept(TANTALUM_CANISTER);
                event.accept(TUNGSTEN_CANISTER);
                event.accept(RHENIUM_CANISTER);
                event.accept(OSMIUM_CANISTER);
                event.accept(IRIDIUM_CANISTER);
                event.accept(PLATINUM_CANISTER);
                event.accept(GOLD_CANISTER);
                event.accept(MERCURY_CANISTER);
                event.accept(THALLIUM_CANISTER);
                event.accept(LEAD_CANISTER);
                event.accept(BISMUTH_CANISTER);
                event.accept(POLONIUM_CANISTER);
                event.accept(ASTATINE_CANISTER);
                event.accept(RADON_CANISTER);
                event.accept(FRANCIUM_CANISTER);
                event.accept(RADIUM_CANISTER);
                event.accept(ACTINIUM_CANISTER);
                event.accept(THORIUM_CANISTER);
                event.accept(PROTACTINIUM_CANISTER);
                event.accept(URANIUM_CANISTER);

                // Gas
                event.accept(COMPRESSED_HYDROGEN);
                event.accept(COMPRESSED_HELIUM);
                event.accept(COMPRESSED_LITHIUM);
                event.accept(COMPRESSED_BERYLLIUM);
                event.accept(COMPRESSED_BORON);
                event.accept(COMPRESSED_CARBON);
                event.accept(COMPRESSED_NITROGEN);
                event.accept(COMPRESSED_OXYGEN);
                event.accept(COMPRESSED_FLUORINE);
                event.accept(COMPRESSED_NEON);
                event.accept(COMPRESSED_SODIUM);
                event.accept(COMPRESSED_MAGNESIUM);
                event.accept(COMPRESSED_ALUMINIUM);
                event.accept(COMPRESSED_SILICON);
                event.accept(COMPRESSED_PHOSPHORUS);
                event.accept(COMPRESSED_SULFUR);
                event.accept(COMPRESSED_CHLORINE);
                event.accept(COMPRESSED_ARGON);
                event.accept(COMPRESSED_POTASSIUM);
                event.accept(COMPRESSED_CALCIUM);
                event.accept(COMPRESSED_SCANDIUM);
                event.accept(COMPRESSED_TITANIUM);
                event.accept(COMPRESSED_VANADIUM);
                event.accept(COMPRESSED_CHROMIUM);
                event.accept(COMPRESSED_MANGANESE);
                event.accept(COMPRESSED_IRON);
                event.accept(COMPRESSED_COBALT);
                event.accept(COMPRESSED_NICKEL);
                event.accept(COMPRESSED_COPPER);
                event.accept(COMPRESSED_ZINC);
                event.accept(COMPRESSED_GALLIUM);
                event.accept(COMPRESSED_GERMANIUM);
                event.accept(COMPRESSED_ARSENIC);
                event.accept(COMPRESSED_SELENIUM);
                event.accept(COMPRESSED_BROMINE);
                event.accept(COMPRESSED_KRYPTON);
                event.accept(COMPRESSED_RUBIDIUM);
                event.accept(COMPRESSED_STRONTIUM);
                event.accept(COMPRESSED_YTTRIUM);
                event.accept(COMPRESSED_ZIRCONIUM);
                event.accept(COMPRESSED_NIOBIUM);
                event.accept(COMPRESSED_MOLYBDENUM);
                event.accept(COMPRESSED_TECHNETIUM);
                event.accept(COMPRESSED_RUTHENIUM);
                event.accept(COMPRESSED_RHODIUM);
                event.accept(COMPRESSED_PALLADIUM);
                event.accept(COMPRESSED_SILVER);
                event.accept(COMPRESSED_CADMIUM);
                event.accept(COMPRESSED_INDIUM);
                event.accept(COMPRESSED_TIN);
                event.accept(COMPRESSED_ANTIMONY);
                event.accept(COMPRESSED_TELLURIUM);
                event.accept(COMPRESSED_IODINE);
                event.accept(COMPRESSED_XENON);
                event.accept(COMPRESSED_CESIUM);
                event.accept(COMPRESSED_BARIUM);
                event.accept(COMPRESSED_LANTHANUM);
                event.accept(COMPRESSED_CERIUM);
                event.accept(COMPRESSED_PRASEODYMIUM);
                event.accept(COMPRESSED_NEODYMIUM);
                event.accept(COMPRESSED_PROMETHIUM);
                event.accept(COMPRESSED_SAMARIUM);
                event.accept(COMPRESSED_EUROPIUM);
                event.accept(COMPRESSED_GADOLINIUM);
                event.accept(COMPRESSED_TERBIUM);
                event.accept(COMPRESSED_DYSPROSIUM);
                event.accept(COMPRESSED_HOLMIUM);
                event.accept(COMPRESSED_ERBIUM);
                event.accept(COMPRESSED_THULIUM);
                event.accept(COMPRESSED_YTTERBIUM);
                event.accept(COMPRESSED_LUTETIUM);
                event.accept(COMPRESSED_HAFNIUM);
                event.accept(COMPRESSED_TANTALUM);
                event.accept(COMPRESSED_TUNGSTEN);
                event.accept(COMPRESSED_RHENIUM);
                event.accept(COMPRESSED_OSMIUM);
                event.accept(COMPRESSED_IRIDIUM);
                event.accept(COMPRESSED_PLATINUM);
                event.accept(COMPRESSED_GOLD);
                event.accept(COMPRESSED_MERCURY);
                event.accept(COMPRESSED_THALLIUM);
                event.accept(COMPRESSED_LEAD);
                event.accept(COMPRESSED_BISMUTH);
                event.accept(COMPRESSED_POLONIUM);
                event.accept(COMPRESSED_ASTATINE);
                event.accept(COMPRESSED_RADON);
                event.accept(COMPRESSED_FRANCIUM);
                event.accept(COMPRESSED_RADIUM);
                event.accept(COMPRESSED_ACTINIUM);
                event.accept(COMPRESSED_THORIUM);
                event.accept(COMPRESSED_PROTACTINIUM);
                event.accept(COMPRESSED_URANIUM);
            }
        }
    }
}
